// Writes spots/matrix.txt, the one-off owner acceptance set (2026-10-02), from the province places.json.
// Usage: node tooling/gpu-lane/spots/gen-matrix.mjs   (deterministic: same places.json, same file)
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { CAPTURE_RATE } from "../spots.mjs";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
export const PLACES_JSON = "apps/world-studio/public/province/places.json";

/** The three most expensive places by bundle stats (tooling/.reports/16k/walk10/perf-matrix-choice.md). */
export const PLACES = [
  ["place.hist-heartland.greenspring", "greenspring"], // heaviest: 220,819 triangles, 149 objects
  ["place.imperial-fringe.claywater-station", "claywater"], // most lights and fires: 13 lights, 19 flames
  ["place.dunmer-north.riverwalk", "riverwalk"], // most water within 150 m
];
export const STEPS = "steps=w:7,yaw:+1.2,w:6,yaw:-2.0,w:7";
// perf10.txt spot e: the ESE jungle marsh shallow-water walk.
export const ESE = `ese ?view=character&x=4.02&z=4.61&t=22&w=rain&rate=${CAPTURE_RATE} walk=20 x3`;

/** places.json text -> matrix.txt text. Studio x,z = positionM / 1000 (site_packet.py:_xz). */
export function matrix(placesText) {
  const byId = new Map(JSON.parse(placesText).places.map((p) => [p.id, p]));
  const L = ["# GENERATED by `node tooling/gpu-lane/spots/gen-matrix.mjs` from " + PLACES_JSON + "; do not edit.",
    "# One-off owner acceptance 2026-10-02 (docs/phases/lanes/performance-lane.md), not a regression gate."];
  for (const [id, short] of PLACES) {
    const p = byId.get(id);
    if (!p?.positionM) throw new Error(`${id}: no positionM in ${PLACES_JSON}`);
    const [x, z] = p.positionM.map((m) => (m / 1000).toFixed(4));
    for (const t of [12, 22]) for (const w of ["clear", "rain"]) {
      L.push(`${short}-t${t}-${w} ?view=character&x=${x}&z=${z}&t=${t}&w=${w}&rate=${CAPTURE_RATE} ${STEPS}`);
    }
  }
  L.push(ESE);
  return L.join("\n") + "\n";
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(here("./matrix.txt"), matrix(readFileSync(here(`../../../${PLACES_JSON}`), "utf8")));
  console.log("wrote tooling/gpu-lane/spots/matrix.txt");
}
