import roster from "./generated/races.json";

/**
 * The playable roster: ten races on two sexes (decision 0054).
 *
 * A **race** is lore — a label, a description, and later the stat and birthsign
 * tables and the `raceIs` dialogue condition. A **character build** is a race
 * and a sex together, because that pair is the granularity at which a GLB
 * exists: `nord-male`, `nord-female`. The character creator coming in phase 10b
 * takes race and sex as separate inputs, so the runtime keeps them separate
 * rather than making every consumer split a flattened id back apart.
 *
 * The roster is generated by the asset pipeline; this file only says what a
 * race and a build mean to the game.
 */

export type Sex = "male" | "female";

export const SEXES: readonly Sex[] = ["male", "female"];

export type RaceId = string;

/** `${RaceId}-${Sex}` — the id of one built body. */
export type CharacterBuildId = string;

/** Lore level. No assets: what a race *is*, not what it looks like. */
export type RaceDefinition = {
  id: RaceId;
  label: string;
  description: string;
};

/** One built body: a race, a sex, and everything the renderer needs. */
export type CharacterBuild = {
  id: CharacterBuildId;
  race: RaceId;
  sex: Sex;
  /** Body GLB, relative to the deployment base URL. */
  asset: string;
  /** Content hash, used to bust a stale browser cache after a rebuild. */
  revision: string;
  /**
   * Biped slots each body mesh occupies, read from the NIF's own dismember
   * partitions at build time. Armour declares the same slots, so "this cuirass
   * hides the torso" is a set intersection rather than a hand-kept list that
   * silently rots when a body mesh is renamed.
   */
  meshBipedSlots: Readonly<Record<string, readonly number[]>>;
  /** How this build is coloured. See `Appearance`. */
  appearance: Appearance;
  /**
   * Skyrim `RACE` record height multiplier for this race *and sex*. The record
   * stores two; a Nord woman is not a Nord man scaled by the male one.
   */
  heightScale: number;
  /** The mesh set (`male`, `male-argonian`, `female`, `female-khajiit`, …). */
  body: string;
  /** The `Skyrim.esm` NPC whose FaceGen head this build ships. */
  faceGen?: { plugin: string; formId: string; editorId: string };
};

/**
 * What makes one character look different from another.
 *
 * Each default body carries one resolved Skyrim FaceGen head: its facial
 * sliders, selected head parts, eyes and generated tint. Body and hair colour
 * remain live inputs. A full character creator can replace the resolved head
 * with its own FaceGen output while using this same runtime contract.
 *
 * Applied at runtime, not baked. That is what a character creator needs — a
 * slider has to move a colour without rebuilding an asset — and it is also the
 * only way it works at all: a tint node between a texture and base colour is
 * not a shape the glTF exporter can write, so a baked one silently ships white.
 */
export type Appearance = {
  /** Skyrim NPC QNAM body-tint bytes, normalised to 0..1 for the shader. */
  skinTint: readonly [number, number, number];
  /** Skyrim's FaceGen RGB tint shader, or an ordinary material multiply. */
  skinTintMode?: "skyrim-rgb-tint" | "multiply";
  /** Skyrim HCLF colour, multiplied over HairTint head parts. */
  hairTint: readonly [number, number, number];
  /** Meshes the skin tint applies to. */
  skinMeshes: readonly string[];
  /** Meshes the hair tint applies to. */
  hairMeshes: readonly string[];
};

const NEUTRAL_APPEARANCE: Appearance = {
  skinTint: [1, 1, 1],
  hairTint: [1, 1, 1],
  skinMeshes: [],
  hairMeshes: [],
};

type BuiltRoster = {
  schemaVersion: number;
  rig: { asset: string; sha256: string };
  sexes?: string[];
  races: Record<string, { id?: string; label: string; description: string }>;
  builds: Record<string, {
    id?: string;
    race: string;
    sex: string;
    asset: string;
    sha256: string;
    body?: string;
    heightScale?: number;
    meshBipedSlots?: Record<string, number[]>;
    appearance?: Appearance;
    faceGen?: { plugin: string; formId: string; editorId: string };
  }>;
  referenceBuilds?: Partial<Record<Sex, string>>;
};

const ROSTER = roster as unknown as BuiltRoster;

/**
 * Engineering standard 3. A version-1 roster carries assets on the race map and
 * knows nothing about sex; loading one would silently ship a male-only game, so
 * it fails at import rather than at the first female selection.
 */
if (ROSTER.schemaVersion !== 2) {
  throw new Error(
    `races.json is schemaVersion ${String(ROSTER.schemaVersion)}, expected 2 — ` +
    "rebuild the roster (tooling/asset-pipeline) before running the game.",
  );
}

export const RACES: Readonly<Record<RaceId, RaceDefinition>> = Object.fromEntries(
  Object.entries(ROSTER.races).map(([id, race]) => [id, {
    id,
    label: race.label,
    description: race.description,
  }]),
);

/** Display order: the roster's, which is the order a player expects to read. */
export const RACE_IDS: readonly RaceId[] = Object.keys(RACES);

export function buildId(race: RaceId, sex: Sex): CharacterBuildId {
  return `${race}-${sex}`;
}

export const CHARACTER_BUILDS: Readonly<Record<CharacterBuildId, CharacterBuild>> =
  Object.fromEntries(
    Object.entries(ROSTER.builds).map(([id, build]) => [id, {
      id,
      race: build.race,
      sex: build.sex as Sex,
      asset: build.asset,
      revision: build.sha256.slice(0, 16),
      meshBipedSlots: build.meshBipedSlots ?? {},
      appearance: build.appearance ?? NEUTRAL_APPEARANCE,
      heightScale: build.heightScale ?? 1,
      body: build.body ?? "male",
      faceGen: build.faceGen,
    }]),
  );

export const CHARACTER_BUILD_IDS: readonly CharacterBuildId[] = Object.keys(CHARACTER_BUILDS);

export function characterBuild(id: CharacterBuildId): CharacterBuild {
  const build = CHARACTER_BUILDS[id];
  if (!build) throw new RangeError(`unknown character build: ${id}`);
  return build;
}

/** True when this race is built for this sex. A partial roster is tolerated. */
export function hasBuild(race: RaceId, sex: Sex): boolean {
  return buildId(race, sex) in CHARACTER_BUILDS;
}

/** The sexes any build exists for, in `SEXES` order. */
export const AVAILABLE_SEXES: readonly Sex[] = SEXES.filter((sex) =>
  RACE_IDS.some((race) => hasBuild(race, sex)));

/** The rig every build is posed by. */
export const RIG_REVISION = ROSTER.rig.sha256.slice(0, 16);

/**
 * The build the support envelopes and fitted hurtbox were measured from, per
 * sex: female bodies, hands and feet are different meshes from the male ones,
 * so one measurement does not cover both (decision 0054).
 *
 * While the roster is still being extended, a sex the pipeline has not built
 * yet resolves to the male reference — the only measured geometry that exists.
 */
export const REFERENCE_BUILDS: Readonly<Record<Sex, CharacterBuildId>> = (() => {
  const declared = ROSTER.referenceBuilds ?? {};
  const fallback = declared.male && declared.male in CHARACTER_BUILDS
    ? declared.male
    : CHARACTER_BUILD_IDS[0];
  const resolve = (sex: Sex) => {
    const named = declared[sex];
    return named && named in CHARACTER_BUILDS ? named : fallback;
  };
  return { male: resolve("male"), female: resolve("female") };
})();

export const DEFAULT_SEX: Sex = "male";

export const DEFAULT_BUILD: CharacterBuildId = REFERENCE_BUILDS[DEFAULT_SEX];

export const DEFAULT_RACE: RaceId = characterBuild(DEFAULT_BUILD).race;

/**
 * Resolve a race and sex to a build, falling back to a sex this race *is*
 * built for. The roster is generated, and while it is mid-extension a race may
 * exist for one sex only; a picker must not be able to crash the renderer.
 */
export function resolveBuild(race: RaceId, sex: Sex): CharacterBuild {
  const exact = CHARACTER_BUILDS[buildId(race, sex)];
  if (exact) return exact;
  for (const other of SEXES) {
    const build = CHARACTER_BUILDS[buildId(race, other)];
    if (build) return build;
  }
  return characterBuild(DEFAULT_BUILD);
}

/**
 * @deprecated Use `characterBuild(buildId(race, sex))`.
 *
 * A race no longer *has* an asset — a build does. This resolves a race id to
 * its default-sex build so that `tooling/asset-pipeline` (owned by another
 * workstream, and outside this change) keeps building; delete it once that
 * script names a build.
 */
export function raceById(id: RaceId): CharacterBuild {
  if (!(id in RACES)) throw new RangeError(`unknown race: ${id}`);
  return resolveBuild(id, DEFAULT_SEX);
}
