/**
 * Dev fixture for the plotted province map (Phase 11 Part 0 item 5).
 *
 * NOT world data and NOT the catalogue: no `place.*` ID here is real, and none
 * of these records may ever be copied into world/sources/catalogue/ (IDs there
 * are permanent). It exists so the map view is reviewable and testable before
 * Part 1 derives the real catalogue — the moment any `places-<region>.json`
 * exists, `loadCatalogue` ignores this file entirely.
 *
 * The records mirror the real schema (catalogue.py) at each workflow rung so
 * the filters, the `why` panel and the `whySiteWon` line all have something to
 * show. IDs use the reserved `fixture` region so they can never collide.
 */
import type { RegionCatalogue } from "./catalogueData";

export const FIXTURE_CATALOGUE: RegionCatalogue[] = [
  {
    region: "fixture-north",
    seed: "fixture",
    places: [
      {
        id: "place.fixture-north.stormhold-toll",
        name: "Stormhold Toll",
        classification: { class: "works", family: "transit", type: "toll", magnitude: "M1" },
        status: "active",
        provenance: "geography-derived",
        sources: ["fixture"],
        confidence: "low",
        importanceTier: 2,
        workflow: "plotted",
        dangerTier: 2,
        discovery: "road",
        complexityBudget: "simple",
        why: {
          founding: "The Imperial road narrows to a causeway here.",
          siteAdvantages: "Only dry crossing for 3 km; sightline both ways.",
          occupantsMotive: "Coin from every cart that must pass.",
          pressures: "Marsh undercuts the causeway each wet season.",
          wouldChangeIf: "A second ford opens downstream.",
        },
        sitingPrefs: { regionClasses: ["floodplain"], hardConstraints: [], preferences: [] },
        position: { u: 0.371, v: 0.121 },
        whySiteWon: "Highest of four candidate narrows and the only one on the road corridor.",
        candidatesConsidered: 4,
        sockets: { scene: [], evidence: [], station: [], marks: [] },
        deedCounterKeys: [],
      },
      {
        id: "place.fixture-north.reed-cut-camp",
        name: "Reed-Cut Camp",
        classification: { class: "camp", family: "civil", type: "hunter", magnitude: null },
        status: "seasonal",
        provenance: "density-fill",
        sources: ["fixture"],
        confidence: "low",
        importanceTier: 4,
        workflow: "plotted",
        dangerTier: 3,
        discovery: "sightline",
        complexityBudget: "trivial",
        why: {
          founding: "Reed cutters follow the draw-down each dry season.",
          siteAdvantages: "Firm hummock inside a reed belt.",
          occupantsMotive: "Cut, bundle, sell at Stormhold.",
          pressures: "Flooded out three months a year.",
          wouldChangeIf: "The reed belt is over-cut.",
        },
        sitingPrefs: { regionClasses: ["marsh"], hardConstraints: [], preferences: [] },
        position: { u: 0.402, v: 0.163 },
        whySiteWon: "Only hummock above wet-season water inside the reed belt.",
        candidatesConsidered: 7,
        sockets: { scene: [], evidence: [], station: [], marks: [] },
        deedCounterKeys: [],
      },
      {
        id: "place.fixture-north.sunken-xanmeer",
        name: "The Sunken Xanmeer",
        classification: { class: "ruin", family: "xanmeer", type: "collapsed", magnitude: null },
        status: "drowned",
        provenance: "lore-implied",
        sources: ["fixture"],
        confidence: "medium",
        importanceTier: 1,
        workflow: "derived",
        dangerTier: 4,
        discovery: "rumour",
        complexityBudget: "standard",
        why: {
          founding: "Built when the basin was dry.",
          siteAdvantages: "Stone shelf above the old channel.",
          occupantsMotive: "Nobody lives here now.",
          pressures: "Water rose and never left.",
          wouldChangeIf: "The basin drains.",
        },
        sitingPrefs: { regionClasses: ["lake"], hardConstraints: ["submerged"], preferences: [] },
        sockets: { scene: [], evidence: [], station: [], marks: [] },
        deedCounterKeys: [],
      },
    ],
  },
  {
    region: "fixture-south",
    seed: "fixture",
    places: [
      {
        id: "place.fixture-south.lilmoth-mooring",
        name: "Lilmoth Outer Mooring",
        classification: { class: "works", family: "transit", type: "dock", magnitude: "M2" },
        status: "active",
        provenance: "canon-named",
        sources: ["fixture"],
        confidence: "high",
        importanceTier: 0,
        workflow: "authored",
        dangerTier: 2,
        discovery: "sightline",
        complexityBudget: "standard",
        why: {
          founding: "Deep water close in, sheltered from the swell.",
          siteAdvantages: "Natural harbour arm; short haul to the city.",
          occupantsMotive: "Every hull too deep for the inner quays ties up here.",
          pressures: "Silt; smugglers; the tide race at spring flood.",
          wouldChangeIf: "The channel silts closed.",
        },
        sitingPrefs: { regionClasses: ["coast"], hardConstraints: [], preferences: [] },
        position: { u: 0.53, v: 0.884 },
        whySiteWon: "The only sheltered deep-water arm within a day of the city.",
        candidatesConsidered: 9,
        sockets: { scene: [], evidence: [], station: [], marks: [] },
        deedCounterKeys: [],
      },
      {
        id: "place.fixture-south.grave-stakes-flat",
        name: "The Grave-Stakes Flat",
        classification: { class: "sacred", family: "worship", type: "grave-stakes-field", magnitude: null },
        status: "active",
        provenance: "lore-implied",
        sources: ["fixture"],
        confidence: "medium",
        importanceTier: 3,
        workflow: "plotted",
        dangerTier: 3,
        discovery: "none",
        complexityBudget: "simple",
        why: {
          founding: "The village buries its dead on the tidal flat.",
          siteAdvantages: "Ground nobody else wants; visible at low water only.",
          occupantsMotive: "The dead go back to the water.",
          pressures: "Outsiders read it as a ruin and dig.",
          wouldChangeIf: "The village moves inland.",
        },
        sitingPrefs: { regionClasses: ["tidal-flat"], hardConstraints: [], preferences: [] },
        position: { u: 0.487, v: 0.842 },
        whySiteWon: "Widest tidal flat within sight of the settlement.",
        candidatesConsidered: 3,
        sockets: { scene: [], evidence: [], station: [], marks: [] },
        deedCounterKeys: [],
      },
      {
        id: "place.fixture-south.drowned-toll",
        name: "The Drowned Toll",
        classification: { class: "ruin", family: "drowned", type: "works", magnitude: null },
        status: "cut",
        provenance: "density-fill",
        sources: ["fixture"],
        confidence: "low",
        importanceTier: 4,
        workflow: "derived",
        dangerTier: 2,
        discovery: "none",
        complexityBudget: "trivial",
        why: {
          founding: "Cut in review — duplicated a better toll 400 m away.",
          siteAdvantages: "None that the neighbour does not have.",
          occupantsMotive: "n/a",
          pressures: "n/a",
          wouldChangeIf: "n/a",
        },
        sitingPrefs: { regionClasses: ["marsh"], hardConstraints: [], preferences: [] },
        sockets: { scene: [], evidence: [], station: [], marks: [] },
        deedCounterKeys: [],
      },
    ],
  },
];
