"""Generate docs/quests/index/ from world/sources/quests/.

    python3 -m worldgen.export_quest_index

The quest index used to be a hand-maintained markdown table
(docs/quests/55-quest-index.md). It could not be written by eight region agents
at once and nothing checked it. The data now lives in world/sources/quests/;
this module renders the reading views:

    main.md            the main-quest spine
    factions.md        the twelve lines' spine tables
    standalone.md      LQ / DQ / ST / ex-main rows
    proposed.md        the PP proposals, not authored
    local-<region>.md  one per catalogue region, empty until a region agent writes
    coverage.md        the commissioning brief: shape gaps, per-region budget and
                       the Morrowind DEMAND LADDER (settlement magnitude -> target
                       quest band) against what is anchored there today

Every generated file carries a GENERATED header; worldgen/test_quests.py asserts
they are byte-identical to a fresh render, the same way test_export_places does
for places.json. The hand-written README.md in that directory (§47a-c: why the
index exists, the shape taxonomy, the novelty rule) is NOT generated.
"""

from __future__ import annotations

import sys
from collections import Counter, defaultdict
from pathlib import Path

from . import catalogue, quests as Q

OUT_DIR = Q.REPO_ROOT / "docs" / "quests" / "index"

HEADER = ("<!-- GENERATED by `python3 -m worldgen.export_quest_index` from "
          "world/sources/quests/. Do not edit by hand: edit the data, then "
          "re-run. Rules and taxonomy live in README.md. -->\n")


def _esc(text: str) -> str:
    return text.replace("|", "\\|")


def _shapes(q: dict) -> str:
    return ", ".join(f"`{s}`" for s in q["shapes"])


def _places(q: dict) -> str:
    if not q["anchorPlaces"]:
        return "—"
    return "<br>".join(f"`{p.removeprefix('place.')}`" for p in q["anchorPlaces"])


def _rows(qs: list[dict]) -> list[str]:
    out = ["| ID | Title | Region | Shapes | Premise | Anchor places | Status |",
           "|---|---|---|---|---|---|---|"]
    for q in sorted(qs, key=lambda q: q["code"]):
        out.append(f"| {q['code']} | {_esc(q['title'])} | {q['region'] or '—'} | "
                   f"{_shapes(q)} | {_esc(q['premise'])} | {_places(q)} | {q['status']} |")
    return out


def _by_group(quests: list[dict]) -> dict[str, list[dict]]:
    g: dict[str, list[dict]] = defaultdict(list)
    for q in quests:
        g[q["group"]].append(q)
    return g


# --------------------------------------------------------------------------- views

def render_main(quests, lines) -> str:
    line = next(l for l in lines if l["id"] == "quest.line.main")
    qs = [q for q in quests if q["line"] == "quest.line.main"]
    body = [HEADER, f"# Main quest — *{line['name']}*", "",
            f"{len(qs)} rows. Merged numbering (decision 0026); tier 0, so no lower "
            f"tier may write anything these quests own.", "", *_rows(qs), ""]
    return "\n".join(body)


def render_factions(quests, lines) -> str:
    faction_lines = [l for l in lines if l["group"] == "faction"]
    by_line = defaultdict(list)
    for q in quests:
        by_line[q["line"]].append(q)
    body = [HEADER, "# Faction lines", "",
            "The spine table first, then one section per line. Full briefs stay in "
            "[../40-factions.md](../40-factions.md).", "",
            "| Line | Code | Faction | Home region | Rows | Mature target | Dominant primary shapes |",
            "|---|---|---|---|---:|---|---|"]
    for l in faction_lines:
        qs = by_line.get(l["id"], [])
        top = Counter(q["shapes"][0] for q in qs).most_common(3)
        body.append(f"| {l['name']} | {l['code']} | `{l['faction']}` | {l['homeRegion']} | "
                    f"{len(qs)} | {l['targetCount']['min']}–{l['targetCount']['max']} | "
                    + ", ".join(f"`{s}`×{n}" for s, n in top) + " |")
    for l in faction_lines:
        qs = by_line.get(l["id"], [])
        body += ["", f"## {l['name']} ({l['code']})", "", l["notes"], "", *_rows(qs)]
    body.append("")
    return "\n".join(body)


def render_standalone(quests, lines) -> str:
    groups = _by_group([q for q in quests
                        if q["line"] in ("quest.line.local", "quest.line.daedric")
                        or q["code"].startswith("ST")])
    body = [HEADER, "# Standalone and local quests", "",
            "Local quests (LQ), the three ex-main rows now regional (MQ11/12/19), the "
            "Daedric and oddity packet (DQ) and the Salt-Teeth pirate branch (ST) — "
            "which is a branch of the Reed-Sail line, not a line of its own.", ""]
    for title, qs in [("Local (LQ, MQ11/12/19)", groups.get("local", [])),
                      ("Daedric and oddity (DQ)", groups.get("daedric", [])),
                      ("Salt-Teeth branch (ST)", [q for q in quests if q["code"].startswith("ST")])]:
        body += [f"## {title}", "", *_rows(qs), ""]
    return "\n".join(body)


def render_proposed(quests) -> str:
    qs = [q for q in quests if q["group"] == "proposed"]
    body = [HEADER, "# Proposed rows from the plotted province — **not authored**", "",
            "Raised by the quest/world co-design pass of 2026-09-04 (decision 0041 "
            "§ Part 4 step 2). No brief, no cast; any of them may be dropped. An author "
            "picking one up re-runs the §47c collision test, because the index has moved "
            "since these were written.", "", *_rows(qs), ""]
    return "\n".join(body)


def render_local(region: str, quests) -> str:
    qs = [q for q in quests if q["group"] == "local" and q["region"] == region]
    body = [HEADER, f"# Local quests — {region}", "",
            f"Data file: `world/sources/quests/local-{region}.json`. This region's agent "
            f"owns that file and nothing else, so eight regions can be written at once.", ""]
    if qs:
        body += _rows(qs)
    else:
        body.append("_No local quests written into this region's packet yet._ "
                    "Rows for this region that still sit in the migrated standalone packet "
                    "are listed in [standalone.md](standalone.md).")
    body.append("")
    return "\n".join(body)


def render_coverage(quests, lines, places, regions) -> str:
    body = [HEADER, "# Coverage — the commissioning brief", "",
            "Generated from the quest data and the live place catalogue. The gaps here "
            "*are* the brief for the next packet.", ""]

    # 1. shape coverage
    primary = Counter(q["shapes"][0] for q in quests)
    secondary = Counter(s for q in quests for s in q["shapes"][1:])
    body += ["## Shape coverage (whole province)", "",
             "| Shape | Primary | Secondary | Verdict |", "|---|---:|---:|---|"]
    for s in Q.SHAPES:
        p, sec = primary.get(s, 0), secondary.get(s, 0)
        verdict = "**gap — first call**" if p <= 2 else ("thin" if p <= 5 else "covered")
        body.append(f"| `{s}` | {p} | {sec} | {verdict} |")
    body.append("")

    # 2. per-region shape budget
    body += ["## Per-region primary-shape budget", "",
             "55 §47c: no primary shape above ~20% of a packet. Regions are the catalogue "
             "packets; a region with few quests trips this easily and that is the point.", "",
             "| Region | Quests | Distinct primary shapes | Heaviest shape | Share |",
             "|---|---:|---:|---|---:|"]
    by_region = defaultdict(list)
    for q in quests:
        by_region[q["region"]].append(q)
    for region in regions:
        qs = by_region.get(region, [])
        c = Counter(q["shapes"][0] for q in qs)
        top = c.most_common(1)
        share = f"{top[0][1] / len(qs):.0%}" if qs else "—"
        body.append(f"| {region} | {len(qs)} | {len(c)} | "
                    f"{('`' + top[0][0] + '`') if top else '—'} | {share} |")
    body.append("")

    # 3. the demand ladder
    anchored: Counter = Counter()
    for q in quests:
        if q["settlement"]:
            anchored[q["settlement"]] += 1
    setts = [r for r in places.values() if r["classification"]["class"] == "settlement"]
    setts.sort(key=lambda r: (-Q.DEMAND_BAND.get(r["classification"].get("magnitude"), (0, 0))[1],
                              r["id"]))
    demand_lo = sum(Q.DEMAND_BAND.get(r["classification"].get("magnitude"), (0, 0))[0] for r in setts)
    demand_hi = sum(Q.DEMAND_BAND.get(r["classification"].get("magnitude"), (0, 0))[1] for r in setts)
    body += ["## The demand ladder (Morrowind density, research §4)", "",
             f"{len(setts)} live settlements. Target band per magnitude: "
             + ", ".join(f"{m} {lo}–{hi}" for m, (lo, hi) in Q.DEMAND_BAND.items()) + ".", "",
             f"Summed settlement demand: **{demand_lo}–{demand_hi}** quests. "
             f"Province target: **{Q.PROVINCE_TARGET[0]}–{Q.PROVINCE_TARGET[1]}** at maturity, "
             f"**{Q.MILESTONE_1_TARGET[0]}–{Q.MILESTONE_1_TARGET[1]}** at Milestone 1. "
             f"Written today: **{len(quests)}** rows "
             f"({sum(1 for q in quests if q['status'] == 'live')} live).", "",
             f"**Read the bands as ceilings, not quotas.** The province plotted "
             f"{len(setts)} live settlements against Morrowind's 35, so applying every "
             f"band at its floor would demand {demand_lo} quests — above the province "
             f"target. The ladder sizes each settlement RELATIVE to its neighbours; the "
             f"{Q.PROVINCE_TARGET[0]}–{Q.PROVINCE_TARGET[1]} total is the binding number, "
             f"so the M5/M4 rows should reach their bands and the long M3/M2 tail should "
             f"sit at the low end, many of them on one quest or none.", "",
             "| Settlement | Region | Mag | Target | Anchored | Short by |",
             "|---|---|---|---|---:|---:|"]
    for r in setts:
        mag = r["classification"].get("magnitude")
        lo, hi = Q.DEMAND_BAND.get(mag, (0, 0))
        n = anchored.get(r["id"], 0)
        body.append(f"| {_esc(r.get('name') or r['id'])} | {r['id'].split('.')[1]} | {mag or '—'} | "
                    f"{lo}–{hi} | {n} | {max(0, lo - n)} |")
    body.append("")

    # 4. per-region totals
    body += ["## Per-region totals against the province target", "",
             "| Region | Settlements | Settlement demand | Quests today | Milestone 1 |",
             "|---|---:|---|---:|---:|"]
    for region in regions:
        rs = [r for r in setts if r["id"].split(".")[1] == region]
        lo = sum(Q.DEMAND_BAND.get(r["classification"].get("magnitude"), (0, 0))[0] for r in rs)
        hi = sum(Q.DEMAND_BAND.get(r["classification"].get("magnitude"), (0, 0))[1] for r in rs)
        qs = by_region.get(region, [])
        body.append(f"| {region} | {len(rs)} | {lo}–{hi} | {len(qs)} | "
                    f"{sum(1 for q in qs if q['milestone'] == 1)} |")
    body += ["", "## Line targets", "",
             "| Line | Group | Rows | Mature target |", "|---|---|---:|---|"]
    counts = Counter(q["line"] for q in quests)
    for l in lines:
        body.append(f"| {l['name']} | {l['group']} | {counts.get(l['id'], 0)} | "
                    f"{l['targetCount']['min']}–{l['targetCount']['max']} |")
    body.append("")
    return "\n".join(body)


# --------------------------------------------------------------------------- run

def build(quest_dir: Path = Q.QUEST_DIR,
          catalogue_dir: Path = catalogue.CATALOGUE_DIR) -> dict[str, str]:
    quests = Q.load_quests(quest_dir)
    lines = Q.load_lines(quest_dir)
    places = Q.live_places(catalogue_dir)
    regions = Q.region_names(catalogue_dir)
    files = {"main.md": render_main(quests, lines),
             "factions.md": render_factions(quests, lines),
             "standalone.md": render_standalone(quests, lines),
             "proposed.md": render_proposed(quests),
             "coverage.md": render_coverage(quests, lines, places, regions)}
    for region in regions:
        files[f"local-{region}.md"] = render_local(region, quests)
    return dict(sorted(files.items()))


def export(out_dir: Path = OUT_DIR, **kw) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in build(**kw).items():
        path = out_dir / name
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    for path in export():
        print(f"wrote {path.relative_to(Q.REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
