"""Place names and quest titles as text-catalogue entries (standard 2/4).

A place record's `name` and a quest row's `title` are player-visible strings.
They live in the world records — those records are the authority — but nothing
may render them raw: the renderer looks the string up by a stable text ID
(`text.place.<slug>.name`, `text.quest.<slug>.title`, where `<slug>` is the
record id with its `place.` / `quest.` prefix dropped, because the ID already
says which namespace it is in).

    python3 -m worldgen.place_text --emit-text   # the two text-catalogue files
    python3 -m worldgen.place_text --check       # are those files current?

Same convention as `worldgen.hydrology_names`: deterministic, sorted by the
record id, byte-identical output for the same input, and the generated file is
gated by a test so a record edit that skips the regeneration fails.

Records with a dead status (`cut`, `deferred` for places, `cut` for quests) are
skipped, matching `lint_prose.lint_catalogue`: they are not in the world.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from . import catalogue, quests

REPO_ROOT = catalogue.REPO_ROOT
GENERATED = REPO_ROOT / "packages" / "text-catalogue" / "src" / "generated"
PLACE_TS = GENERATED / "place-names.ts"
QUEST_TS = GENERATED / "quest-titles.ts"

DEAD_PLACE_STATUS = {"cut", "deferred"}
DEAD_QUEST_STATUS = {"cut"}


def place_text_id(place_id: str) -> str:
    return "text.place." + place_id.split(".", 1)[1] + ".name"


def quest_text_id(quest_id: str) -> str:
    return "text.quest." + quest_id.split(".", 1)[1] + ".title"


def place_entries() -> list[dict]:
    rows = []
    for rf in catalogue.load_region_files():
        for rec in rf.places:
            if rec.get("status") in DEAD_PLACE_STATUS:
                continue
            if not isinstance(rec.get("name"), str) or not rec["name"]:
                continue
            cls = rec.get("classification") or {}
            rows.append({"recordId": rec["id"], "id": place_text_id(rec["id"]),
                         "surface": "descriptive", "text": rec["name"],
                         "note": (f"Place name from {rec['id']} "
                                  f"({cls.get('class') or '?'}/"
                                  f"{cls.get('type') or '?'}, {rf.region}, "
                                  f"status {rec.get('status')}). "
                                  "The catalogue record is the authority.")})
    rows.sort(key=lambda r: r["recordId"])
    return rows


def quest_entries() -> list[dict]:
    rows = []
    for q in quests.load_quests():
        if q.get("status") in DEAD_QUEST_STATUS:
            continue
        if not isinstance(q.get("title"), str) or not q["title"]:
            continue
        rows.append({"recordId": q["id"], "id": quest_text_id(q["id"]),
                     "surface": "descriptive", "text": q["title"],
                     "note": (f"Quest title from {q['id']} "
                              f"({q.get('code')}, {q.get('group')}, "
                              f"{q.get('region') or 'province-wide'}, "
                              f"status {q.get('status')}). "
                              "The quest record is the authority.")})
    rows.sort(key=lambda r: r["recordId"])
    return rows


def _ts(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def emit(rows: list[dict], const: str, source: str) -> str:
    body = "".join(
        f"  {{ id: {_ts(r['id'])}, surface: {_ts(r['surface'])}, "
        f"text: {_ts(r['text'])}, note: {_ts(r['note'])} }},\n"
        for r in rows)
    return (
        "// GENERATED by `python3 -m worldgen.place_text --emit-text` "
        f"from {source}.\n"
        "// Do not edit by hand: edit the record and regenerate.\n"
        'import type { TextEntry } from "../catalogue.js";\n\n'
        f"export const {const}: readonly TextEntry[] = [\n"
        f"{body}"
        "];\n")


def emit_places() -> str:
    return emit(place_entries(), "PLACE_NAME_TEXT",
                "world/sources/catalogue/places-*.json")


def emit_quests() -> str:
    return emit(quest_entries(), "QUEST_TITLE_TEXT",
                "world/sources/quests/*.json")


def stale() -> list[str]:
    """Which generated files no longer match the records."""
    out = []
    for path, want in ((PLACE_TS, emit_places()), (QUEST_TS, emit_quests())):
        have = path.read_text(encoding="utf-8") if path.exists() else None
        if have != want:
            name = path.name
            out.append(f"packages/text-catalogue/src/generated/{name} is stale: "
                       "run python3 -m worldgen.place_text --emit-text")
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--emit-text", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    if args.emit_text:
        GENERATED.mkdir(parents=True, exist_ok=True)
        PLACE_TS.write_text(emit_places(), encoding="utf-8")
        QUEST_TS.write_text(emit_quests(), encoding="utf-8")
        print(f"wrote {PLACE_TS.relative_to(REPO_ROOT)} "
              f"({len(place_entries())} places) and "
              f"{QUEST_TS.relative_to(REPO_ROOT)} ({len(quest_entries())} quests)")
    if args.check or not args.emit_text:
        errs = stale()
        for e in errs:
            print("FAIL", e)
        if not errs:
            print(f"place-names.ts and quest-titles.ts are current "
                  f"({len(place_entries())} places, {len(quest_entries())} quests)")
        return 1 if errs else 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
