"""Register digest: one data line per built place (16k S13, method review F3).

    python3 -m worldgen.register_digest          # writes world/sources/placement/register-digest.md

A builder's step 0 reads this digest and its site packet, never every
``*.design.md``. A place is built when it has a design brief
(``world/sources/blueprints/<stem>.design.md``) or an entry in
``accepted-places.json``. Each line is data, generated, never hand-edited:
id, catalogue type and magnitude, position, the shells and signature count
it holds in ``signature-claims.json``, status, and its brief. Deterministic
(sorted by id); exit 0.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from .atomic_write import atomic_write_bytes

REPO_ROOT = Path(__file__).resolve().parents[3]
BLUEPRINTS = REPO_ROOT / "world" / "sources" / "blueprints"
PLACEMENT = REPO_ROOT / "world" / "sources" / "placement"
ACCEPTED = PLACEMENT / "accepted-places.json"
OUT = PLACEMENT / "register-digest.md"
HEADER = ("<!-- GENERATED by `python3 -m worldgen.register_digest` (16k S13); "
          "machine data, never hand-edit: rerun the tool. -->\n")
PLACE_ID = re.compile(r"\bplace\.[a-z0-9-]+\.[a-z0-9-]+\b")


def built_places() -> dict[str, dict]:
    """{place id: {"brief": repo-relative path | None, "accepted": entry | None}}."""
    out: dict[str, dict] = {}
    for brief in sorted(BLUEPRINTS.glob("*.design.md")):
        stem = brief.name.removesuffix(".design.md")
        layout = BLUEPRINTS / f"{stem}.layout.json"
        pid = None
        if layout.exists():
            pid = json.loads(layout.read_text(encoding="utf-8")).get("placeId")
        if pid is None:
            hit = PLACE_ID.search(brief.read_text(encoding="utf-8"))
            pid = hit.group(0) if hit else None
        if pid:
            out.setdefault(pid, {"brief": None, "accepted": None})["brief"] = \
                str(brief.relative_to(REPO_ROOT))
    if ACCEPTED.exists():
        for row in json.loads(ACCEPTED.read_text(encoding="utf-8")).get("places") or []:
            pid = row.get("id") or row.get("placeId")
            if pid:
                out.setdefault(pid, {"brief": None, "accepted": None})["accepted"] = row
    return dict(sorted(out.items()))


def _records() -> dict[str, dict]:
    from . import catalogue
    return {rec["id"]: rec for region in catalogue.load_region_files() for rec in region.places}


def lines() -> list[str]:
    from . import claim_signature as cl
    records = _records()
    claims = cl.load()["claims"]
    rows = []
    for pid, built in built_places().items():
        rec = records.get(pid) or {}
        cls = rec.get("classification") or {}
        pos = rec.get("positionM") or []
        mine = sorted(c["signature"] for c in claims if c["placeId"] == pid)
        shells = sorted({s.split(" | ", 1)[0] for s in mine})
        acc = built["accepted"]
        status = (f"accepted {acc.get('acceptedOn') or acc.get('date') or ''}".strip()
                  if acc else "built, not accepted")
        rows.append(" | ".join([
            f"`{pid}`",
            f"type `{cls.get('type') or '-'}`",
            f"magnitude {cls.get('magnitude') or '-'}",
            "positionM " + (f"[{pos[0]:.0f}, {pos[-1]:.0f}]" if len(pos) >= 2 else "-"),
            f"shells {', '.join(f'`{s}`' for s in shells) or '-'}",
            f"signatures {len(mine)}",
            f"status {status}",
            f"brief `{built['brief'] or '-'}`",
        ]))
    return rows


def render(body: list[str] | None = None) -> str:
    body = lines() if body is None else body
    return (HEADER + "\n# Register digest\n\n"
            + "".join(f"- {row}\n" for row in body)
            + ("" if body else "- (no built place)\n"))


def main(argv: list[str] | None = None) -> int:
    body = lines()
    text = render(body)
    if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
        atomic_write_bytes(OUT, text.encode("utf-8"), 0o644)
    print(f"register_digest: {OUT.relative_to(REPO_ROOT)} ({len(body)} places)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
