"""Publish a ground-material set's albedo array as ONE KTX2 array texture.

    python3 -m pipeline.ground_compress --set bmv-v1          # write
    python3 -m pipeline.ground_compress --all --check         # verify only

The ground splat samples a `sampler2DArray` whose layers are the set's
materials in id order, then the normal maps of `cliff_rock` and `cliff_dirt`
(apps/world-studio/src/groundMaterial.ts). Uploaded from the PNGs that is
42-44 layers x 512² RGBA8 with mips, 59 MB of VRAM. Here every layer goes
through the same encoder as the kits (gltfpack's BasisU, UASTC, quality from
`kit_compress.DEFAULT_POLICY`, mips generated by the encoder) and the layers
are joined into one KTX2 container with `layerCount` = layers, so the
runtime's `KTX2Loader` hands back a `CompressedArrayTexture` that stays BC7 /
ASTC on the GPU (about a quarter of the bytes).

Joining: gltfpack writes each layer as a single-image KTX2 whose levels are
zstd frames. A KTX2 array level holds every layer's image back to back, and a
zstd stream may be several frames, so the array's level k is the
concatenation of the layers' level-k frames (no re-encode). The DFD and the
key/value data are the first layer's; every layer must agree on format, size
and level count, else the build fails.

The PNGs stay published: the settlement ground paint reads single rows of
them (packages/game-core/src/settlement/groundPaintMaterial.ts). Output:
`apps/world-studio/public/textures/ground/<set>/albedo-array.ktx2`; the
layer list and source hashes go to `albedo-array.json` beside it so `--check`
can say the array is stale. Deterministic: same PNGs, same gltfpack, same
bytes (one encoder thread).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import struct
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from pipeline.kit_compress import DEFAULT_POLICY, gltfpack_path

REPO_ROOT = Path(__file__).resolve().parents[3]
GROUND = REPO_ROOT / "apps/world-studio/public/textures/ground"
ARRAY_FILE = "albedo-array.ktx2"
RECORD_FILE = "albedo-array.json"
KTX2_ID = b"\xabKTX 20\xbb\r\n\x1a\n"


def layer_files(manifest: dict) -> list[tuple[str, str]]:
    """(file, class) per layer in the runtime's order: materials by id, then
    the two cliff normals when both exist (groundMaterial.ts `cliffNrmOk`)."""
    mats = sorted(manifest["materials"], key=lambda m: m["id"])
    layers = [(m["file"], "color") for m in mats]
    by_name = {m["name"]: m for m in mats}
    nrm = [by_name.get(n, {}).get("normalFile") for n in ("cliff_rock", "cliff_dirt")]
    if all(nrm):
        layers += [(f, "normal") for f in nrm]
    return layers


def _pad4(b: bytes, fill: bytes = b"\0") -> bytes:
    return b + fill * ((4 - len(b) % 4) % 4)


def wrap_glb(png: bytes, cls: str) -> bytes:
    """A one-triangle GLB whose material uses `png` as base colour (colour
    class) or normal map (normal class), so gltfpack encodes it as the kits'
    textures of that class are encoded."""
    pos = struct.pack("<9f", 0, 0, 0, 1, 0, 0, 0, 1, 0)
    uv = struct.pack("<6f", 0, 0, 1, 0, 0, 1)
    nrm = struct.pack("<9f", 0, 0, 1, 0, 0, 1, 0, 0, 1)
    tan = struct.pack("<12f", 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1)
    blob = pos + uv + nrm + tan + _pad4(png)
    views = [(0, 36), (36, 24), (60, 36), (96, 48), (144, len(png))]
    attrs = {"POSITION": 0, "TEXCOORD_0": 1, "NORMAL": 2, "TANGENT": 3}
    mat: dict = {"name": "layer"}
    if cls == "normal":
        mat["normalTexture"] = {"index": 0}
    else:
        mat["pbrMetallicRoughness"] = {"baseColorTexture": {"index": 0}}
    j = {
        "asset": {"version": "2.0"}, "scene": 0, "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "name": "layer"}],
        "meshes": [{"primitives": [{"attributes": attrs, "material": 0}]}],
        "materials": [mat],
        "textures": [{"source": 0, "sampler": 0}],
        "samplers": [{"magFilter": 9729, "minFilter": 9987, "wrapS": 10497, "wrapT": 10497}],
        "images": [{"bufferView": 4, "mimeType": "image/png"}],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3", "min": [0, 0, 0], "max": [1, 1, 0]},
            {"bufferView": 1, "componentType": 5126, "count": 3, "type": "VEC2"},
            {"bufferView": 2, "componentType": 5126, "count": 3, "type": "VEC3"},
            {"bufferView": 3, "componentType": 5126, "count": 3, "type": "VEC4"},
        ],
        "bufferViews": [{"buffer": 0, "byteOffset": o, "byteLength": n} for o, n in views],
        "buffers": [{"byteLength": len(blob)}],
    }
    js = _pad4(json.dumps(j, separators=(",", ":")).encode(), b" ")
    body = struct.pack("<II", len(js), 0x4E4F534A) + js + struct.pack("<II", len(blob), 0x004E4942) + blob
    return struct.pack("<III", 0x46546C67, 2, 12 + len(body)) + body


def ktx2_from_glb(glb: bytes) -> bytes:
    jlen = struct.unpack("<I", glb[12:16])[0]
    j = json.loads(glb[20:20 + jlen])
    bin0 = 20 + jlen + 8
    bv = j["bufferViews"][j["images"][0]["bufferView"]]
    start = bin0 + bv.get("byteOffset", 0)
    return glb[start:start + bv["byteLength"]]


def parse_ktx2(data: bytes) -> dict:
    if data[:12] != KTX2_ID:
        raise ValueError("not a KTX2 container")
    (vk, type_size, w, h, d, layers, faces, levels, scheme) = struct.unpack("<9I", data[12:48])
    dfd_off, dfd_len, kvd_off, kvd_len = struct.unpack("<4I", data[48:64])
    sgd_off, sgd_len = struct.unpack("<2Q", data[64:80])
    lv = [struct.unpack("<3Q", data[80 + 24 * i:104 + 24 * i]) for i in range(levels)]
    return {
        "vk": vk, "typeSize": type_size, "w": w, "h": h, "d": d, "layers": layers, "faces": faces,
        "levels": levels, "scheme": scheme, "dfd": data[dfd_off:dfd_off + dfd_len],
        "kvd": data[kvd_off:kvd_off + kvd_len], "sgd": data[sgd_off:sgd_off + sgd_len],
        "levelData": [(data[o:o + n], u) for o, n, u in lv],
    }


def join_layers(parts: list[dict]) -> bytes:
    """One KTX2 array container from single-layer containers (module doc)."""
    first = parts[0]
    for i, p in enumerate(parts):
        for k in ("vk", "typeSize", "w", "h", "levels", "scheme"):
            if p[k] != first[k]:
                raise ValueError(f"layer {i}: {k} differs from layer 0")
        # The normal layers are tagged linear and the colour layers sRGB
        # (DFD byte 14, transferFunction); the runtime samples every layer
        # raw (NoColorSpace), so only the transfer byte may differ.
        if p["dfd"][:14] + p["dfd"][15:] != first["dfd"][:14] + first["dfd"][15:]:
            raise ValueError(f"layer {i}: data format descriptor differs from layer 0")
        if p["layers"] > 1 or p["faces"] != 1 or p["sgd"]:
            raise ValueError(f"layer {i}: not a plain single-image UASTC container")
    levels = first["levels"]
    joined = [(b"".join(p["levelData"][k][0] for p in parts), sum(p["levelData"][k][1] for p in parts))
              for k in range(levels)]
    header_len = 80 + 24 * levels
    dfd_off = header_len
    kvd_off = dfd_off + len(first["dfd"])
    cursor = kvd_off + len(first["kvd"])
    # Levels are stored smallest first (KTX2 §3.9), each 8-aligned.
    offsets: list[int] = [0] * levels
    for k in reversed(range(levels)):
        cursor += (8 - cursor % 8) % 8
        offsets[k] = cursor
        cursor += len(joined[k][0])
    out = bytearray(cursor)
    out[:12] = KTX2_ID
    out[12:48] = struct.pack("<9I", first["vk"], first["typeSize"], first["w"], first["h"], 0,
                             len(parts), 1, levels, first["scheme"])
    out[48:64] = struct.pack("<4I", dfd_off, len(first["dfd"]), kvd_off if first["kvd"] else 0, len(first["kvd"]))
    out[64:80] = struct.pack("<2Q", 0, 0)
    for k in range(levels):
        out[80 + 24 * k:104 + 24 * k] = struct.pack("<3Q", offsets[k], len(joined[k][0]), joined[k][1])
    out[dfd_off:kvd_off] = first["dfd"]
    out[kvd_off:kvd_off + len(first["kvd"])] = first["kvd"]
    for k in range(levels):
        out[offsets[k]:offsets[k] + len(joined[k][0])] = joined[k][0]
    return bytes(out)


def encode_layer(png: bytes, cls: str, workdir: Path) -> dict:
    src, dst = workdir / "in.glb", workdir / "out.glb"
    src.write_bytes(wrap_glb(png, cls))
    args = [str(gltfpack_path()), "-i", str(src), "-o", str(dst), "-tc", "-tq", str(DEFAULT_POLICY["quality"]),
            "-tu", cls, "-tj", "1", "-kn", "-km"]
    subprocess.run(args, check=True, capture_output=True)
    return parse_ktx2(ktx2_from_glb(dst.read_bytes()))


def sources_record(set_dir: Path) -> dict:
    manifest = json.loads((set_dir / "materials.json").read_text())
    layers = layer_files(manifest)
    return {
        "schemaVersion": 1,
        "encoder": {"tool": "gltfpack 1.2 (BasisU)", "mode": "uastc", "quality": DEFAULT_POLICY["quality"]},
        "layers": [{"file": f, "class": c,
                    "sha256": hashlib.sha256((set_dir / f).read_bytes()).hexdigest()} for f, c in layers],
    }


def build(set_id: str) -> dict:
    set_dir = GROUND / set_id
    record = sources_record(set_dir)
    with tempfile.TemporaryDirectory() as tmp:
        def one(i_layer: tuple[int, dict]) -> dict:
            i, L = i_layer
            work = Path(tmp) / str(i)
            work.mkdir()
            return encode_layer((set_dir / L["file"]).read_bytes(), L["class"], work)
        # Each layer is encoded on its own (one encoder thread each, so the
        # bytes do not depend on scheduling); the pool only runs them side by side.
        with ThreadPoolExecutor(max_workers=4) as pool:
            parts = list(pool.map(one, enumerate(record["layers"])))
    array = join_layers(parts)
    (set_dir / ARRAY_FILE).write_bytes(array)
    record["bytes"] = len(array)
    record["sha256"] = hashlib.sha256(array).hexdigest()
    (set_dir / RECORD_FILE).write_text(json.dumps(record, indent=1) + "\n")
    return record


def check(set_id: str) -> list[str]:
    set_dir = GROUND / set_id
    rec_path, arr_path = set_dir / RECORD_FILE, set_dir / ARRAY_FILE
    if not rec_path.exists() or not arr_path.exists():
        return [f"{set_id}: {ARRAY_FILE} or {RECORD_FILE} missing (run pipeline.ground_compress --set {set_id})"]
    rec = json.loads(rec_path.read_text())
    want = sources_record(set_dir)
    problems = []
    if [(L["file"], L["sha256"]) for L in rec["layers"]] != [(L["file"], L["sha256"]) for L in want["layers"]]:
        problems.append(f"{set_id}: {ARRAY_FILE} is stale against the set's PNGs")
    if hashlib.sha256(arr_path.read_bytes()).hexdigest() != rec.get("sha256"):
        problems.append(f"{set_id}: {ARRAY_FILE} does not match its record's sha256")
    hdr = parse_ktx2(arr_path.read_bytes())
    if hdr["layers"] != len(want["layers"]):
        problems.append(f"{set_id}: {hdr['layers']} layers, the set has {len(want['layers'])}")
    return problems


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--set")
    g.add_argument("--all", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    sets = [a.set] if a.set else sorted(json.loads((GROUND / "index.json").read_text())["sets"])
    bad = []
    for s in sets:
        if a.check:
            bad += check(s)
        else:
            r = build(s)
            print(f"{s}: {len(r['layers'])} layers, {r['bytes'] / 1e6:.2f} MB")
    for p in bad:
        print(p, file=sys.stderr)
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
