#!/usr/bin/env node
/**
 * Counts the docs keep getting wrong, computed from the committed data.
 * `node tooling/repo-standards/facts.mjs --write` regenerates docs/FACTS.md;
 * check.mjs (standard 15e) fails a live doc that states a different number
 * next to one of these nouns. Live prose links to FACTS.md instead of
 * copying a number; a number that must appear in prose sits on a dated line.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const ROOT = join(HERE, "..", "..");
const readJson = (p) => JSON.parse(readFileSync(join(ROOT, p), "utf8"));
const count = (dir, suffix) => (existsSync(join(ROOT, dir)) ? readdirSync(join(ROOT, dir)).filter((f) => f.endsWith(suffix)).length : 0);

export function computeFacts() {
  const facts = {};
  const src = {};
  // catalogue
  const catDir = "world/sources/catalogue";
  let records = [];
  for (const f of readdirSync(join(ROOT, catDir)).filter((f) => /^places-.*\.json$/.test(f))) {
    const d = readJson(join(catDir, f));
    const rows = Array.isArray(d) ? d : d.places ?? d.records ?? [];
    records = records.concat(rows);
  }
  facts.catalogueRecords = records.length; src.catalogueRecords = `${catDir}/places-*.json`;
  facts.dungeonKindRecords = records.filter((r) => r.interior && ["delve", "dungeon", "warren", "complex"].includes(r.interior.kind)).length; src.dungeonKindRecords = "interior.kind in delve|dungeon|warren|complex";
  facts.sitedRecords = records.filter((r) => Array.isArray(r.positionM)).length; src.sitedRecords = "records with positionM";
  // animation manifest
  const anim = "packages/game-core/src/anim/generated/rig-skyrim-humanoid.animations.json";
  if (existsSync(join(ROOT, anim))) { const a = readJson(anim); facts.animationClips = Object.keys(a.animations ?? {}).length; src.animationClips = anim; }
  // hydrology graph
  const graph = "world/sources/hydrology/hydrology-graph.json";
  if (existsSync(join(ROOT, graph))) { const g = readJson(graph); const s = g.stats ?? {}; facts.hydrologyRivers = s.rivers; facts.hydrologyReaches = s.reaches; facts.hydrologyBodies = s.bodies; facts.hydrologyFalls = s.falls; for (const k of ["hydrologyRivers", "hydrologyReaches", "hydrologyBodies", "hydrologyFalls"]) src[k] = `${graph} stats`; }
  // ferries
  const ferries = "world/sources/routes/ferry-crossings.json";
  if (existsSync(join(ROOT, ferries))) { const f = readJson(ferries); const s = f.services ?? f; facts.ferryServices = Array.isArray(s) ? s.length : Object.keys(s).length; src.ferryServices = ferries; }
  // kits, bodies, standards
  facts.publishedKits = count("apps/world-studio/public/kits", ".kit.json"); src.publishedKits = "apps/world-studio/public/kits/*.kit.json";
  facts.builtBodies = count("packages/character-assets/files/races", ".glb"); src.builtBodies = "packages/character-assets/files/races/*.glb";
  const std = readFileSync(join(ROOT, "docs/standards/engineering.md"), "utf8");
  facts.engineeringStandards = (std.match(/^## \d+\./gm) ?? []).length; src.engineeringStandards = "docs/standards/engineering.md `## N.` headings";
  return { facts, src };
}

export function renderFacts({ facts, src }) {
  const rows = Object.keys(facts).map((k) => `| ${k} | ${facts[k]} | ${src[k]} |`).join("\n");
  return `# Facts — counts computed from the committed data

Generated by \`node tooling/repo-standards/facts.mjs --write\` (also \`npm run facts\`).
Do not edit by hand. Live prose links here instead of copying a number; a
number that must appear in prose sits on a dated line. Standard 15 fails a
live doc that states a different number next to one of these nouns.

| Fact | Value | Source |
|---|---|---|
${rows}
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const out = renderFacts(computeFacts());
  if (process.argv.includes("--write")) { writeFileSync(join(ROOT, "docs/FACTS.md"), out); console.log("wrote docs/FACTS.md"); }
  else process.stdout.write(out);
}
