import * as THREE from "three";
import type { ApertureLight } from "./froxelGrid";

import interiorLight from "./interiorLight.json";

/**
 * Window light for an interior cell (decision 0112 §6). Everything about
 * a cell's light comes from interiorLight.json, generated by
 * tooling/volumetrics/interior_light.py over the published bundles (keyed by cell
 * id): the apertures from the plugin's own placed refs (0114), the cell's kind
 * and its dust band. A cell with no window has `apertures: []` and a reason there.
 */
export interface WindowAperture {
  /** Aperture centre, cell frame (the interior group's local space). */
  centre: THREE.Vector3;
  /** Horizontal unit normal, pointing out of the cell. */
  outward: THREE.Vector3;
  areaM2: number;
}

export type DustBand = "low" | "medium" | "high";
export interface InteriorLightRow {
  apertures: { centreM: number[]; outward: number[]; radiusM: number }[];
  kind: string;
  dust: DustBand;
  floorMist: boolean;
}
export interface InteriorLightRecord { schemaVersion: 1; cells: Record<string, InteriorLightRow> }
const RECORD = interiorLight as InteriorLightRecord;

/** The cell's row, or null when the record has none (a cell published after the record was regenerated). */
export function interiorLightOf(cellId: string, record: InteriorLightRecord = RECORD): InteriorLightRow | null {
  return record.cells[cellId] ?? null;
}

/** The froxel medium's dust density per band (1/m), 0112 §6: how visible a sun shaft is in the room. */
export const DUST_DENSITY: Readonly<Record<DustBand, number>> = { low: 0.005, medium: 0.01, high: 0.02 };

/** The plugin-placed apertures of a cell, [] when it places none. */
export function pluginWindowApertures(cellId: string, record: InteriorLightRecord = RECORD): WindowAperture[] {
  const cell = interiorLightOf(cellId, record);
  if (!cell) return [];
  return cell.apertures.map((a) => ({
    centre: new THREE.Vector3(a.centreM[0], a.centreM[1], a.centreM[2]),
    outward: new THREE.Vector3(a.outward[0], 0, a.outward[2]).normalize(),
    areaM2: Math.PI * a.radiusM * a.radiusM,
  }));
}

/**
 * How far the cell's compass is turned from the world's, in degrees clockwise
 * (0112 §6): the cell's entrance faces the way the exterior door it was entered by
 * faces. `entranceFacingDeg` is that door's outward compass bearing (the
 * settlement door's `facingDeg`); the plugin's arrival marker faces INTO the
 * room, so the cell's own outward bearing is `arrivalYawDeg + 180`. A world
 * bearing b is cell bearing b - offset.
 */
export function cellCompassOffsetDeg(entranceFacingDeg: number, arrivalYawDeg: number): number {
  return (((entranceFacingDeg - arrivalYawDeg - 180) % 360) + 540) % 360 - 180;
}

/** A world-frame direction turned into the cell frame (`out` may alias `dir`). */
export function worldToCellDirection(dir: THREE.Vector3, offsetDeg: number, out: THREE.Vector3): THREE.Vector3 {
  // bearing b -> b - offset: a clockwise compass turn is a +angle turn about +y in x-east/z-south axes.
  return out.copy(dir).applyAxisAngle(_Y, THREE.MathUtils.degToRad(offsetDeg));
}
const _Y = new THREE.Vector3(0, 1, 0);

export const MAX_WINDOW_BEAMS = 4;
/** Sky fill through a window the sun is not behind, relative to a sun beam. */
export const SKY_FILL_SCALE = 0.15;
/** Moonlight relative to the sun. */
export const MOON_SCALE = 0.02;
/** A sun beam against the brightest lamp's pool at the floor (0112 §6: 2-4x). */
export const BEAM_OVER_LAMP = 3;
const FILL_TILT = Math.tan(THREE.MathUtils.degToRad(30));

/**
 * The brightest lamp pool at the floor, in the interior's exposure-1 units:
 * a point light of intensity I at height h over the floor lights it with I/h².
 * `lights` are the cell's (interiorLoader: intensity = fade × π, inverse-square).
 */
export function brightestLampFloor(lights: readonly { intensity: number; heightM: number }[]): number {
  let best = 0;
  for (const l of lights) best = Math.max(best, l.intensity / Math.max(1, l.heightM) ** 2);
  return best > 0 ? best : Math.PI / 4;
}

/** Seconds a beam takes to fade fully in or out. */
export const BEAM_FADE_S = 0.6;
/** Floor pieces smaller than this (m², up-facing area at one height in one mesh) are furniture tops, not floors. */
export const FLOOR_MIN_AREA_M2 = 4;
/** Floor heights within this of each other are one level. */
export const FLOOR_CLUSTER_M = 0.3;
/** The player stands on a level when the feet are at most this below it (stairs, slop). */
export const FEET_SLOP_M = 0.3;

/**
 * Floor levels from (height, area) samples: samples under FLOOR_MIN_AREA_M2
 * dropped, the rest sorted and chained into clusters whose neighbours lie
 * within FLOOR_CLUSTER_M; each level is its cluster's area-weighted mean. Ascending.
 */
export function clusterFloorLevels(samples: readonly { y: number; areaM2: number }[]): number[] {
  const s = samples.filter((x) => x.areaM2 > FLOOR_MIN_AREA_M2).sort((a, b) => a.y - b.y);
  const out: number[] = [];
  let sumY = 0, sumA = 0, last = -Infinity;
  for (const x of s) {
    if (x.y - last > FLOOR_CLUSTER_M && sumA > 0) { out.push(sumY / sumA); sumY = 0; sumA = 0; }
    sumY += x.y * x.areaM2; sumA += x.areaM2; last = x.y;
  }
  if (sumA > 0) out.push(sumY / sumA);
  return out;
}

/**
 * The cell's floor levels in its own frame (the group's local space), read once
 * at load from its opaque meshes: up-facing (normal y > 0.95) triangles, their
 * area summed per mesh per 0.1 m of height, then clusterFloorLevels.
 */
export function cellFloorLevels(group: THREE.Object3D): number[] {
  const _a = new THREE.Vector3(), _b = new THREE.Vector3(), _c = new THREE.Vector3(), _n = new THREE.Vector3();
  const _toCell = new THREE.Matrix4();
  group.updateMatrixWorld(true);
  const groupInv = new THREE.Matrix4().copy(group.matrixWorld).invert();
  const samples: { y: number; areaM2: number }[] = [];
  group.traverse((o) => {
    const m = o as THREE.Mesh;
    if (!m.isMesh || (m as unknown as THREE.InstancedMesh).isInstancedMesh) return;
    const mat = Array.isArray(m.material) ? m.material[0] : m.material;
    if (!mat || mat.transparent) return;
    const pos = m.geometry.getAttribute("position");
    if (!pos) return;
    const idx = m.geometry.getIndex();
    _toCell.multiplyMatrices(groupInv, m.matrixWorld);
    const bins = new Map<number, number>();
    const n = idx ? idx.count : pos.count;
    for (let i = 0; i + 2 < n; i += 3) {
      _a.fromBufferAttribute(pos, idx ? idx.getX(i) : i).applyMatrix4(_toCell);
      _b.fromBufferAttribute(pos, idx ? idx.getX(i + 1) : i + 1).applyMatrix4(_toCell);
      _c.fromBufferAttribute(pos, idx ? idx.getX(i + 2) : i + 2).applyMatrix4(_toCell);
      _n.crossVectors(_b.sub(_a), _c.sub(_a)); // _b, _c now edges
      const len = _n.length();
      if (len === 0 || _n.y / len < 0.95) continue;
      const key = Math.round((_a.y + (_b.y + _c.y) / 3) * 10); // centroid y (edges carry the offset)
      bins.set(key, (bins.get(key) ?? 0) + len / 2);
    }
    for (const [k, areaM2] of bins) samples.push({ y: k / 10, areaM2 });
  });
  return clusterFloorLevels(samples);
}

/** The storey of height y: index of the highest level at or below it, -1 below all (or no levels). */
export function storeyOf(y: number, floorsY: readonly number[]): number {
  let best = -1;
  for (let i = 0; i < floorsY.length; i++) if (floorsY[i] <= y && (best < 0 || floorsY[i] > floorsY[best])) best = i;
  return best;
}

/** What the beam ranking reads each frame, all in the cell frame. */
export interface BeamView {
  /** The player's feet. */
  player: THREE.Vector3;
  /** The cell's floor levels (cellFloorLevels); none means one storey. */
  floorsY?: readonly number[];
  /** The camera frustum; an aperture is in view when its sphere of the beam length meets it. */
  frustum: THREE.Frustum;
  beamLengthM: number;
  /** Unit direction the light travels. */
  lightDir: THREE.Vector3;
}

const _sphere = new THREE.Sphere();

/** True when the light enters through this pane (it travels along -outward, from above). */
function sunFacing(w: WindowAperture, lightDir: THREE.Vector3): boolean {
  return -(lightDir.x * w.outward.x + lightDir.z * w.outward.z) > 0.1 && lightDir.y < 0;
}

function sameStorey(y: number, v: BeamView): boolean {
  const floors = v.floorsY ?? [];
  return storeyOf(y, floors) === storeyOf(v.player.y + FEET_SLOP_M, floors);
}

/**
 * Window indices best first (planner ruling, 0112 §6): same storey as the
 * player, then in view, then sun-facing, then nearest. Written into `out`.
 */
export function rankApertures(windows: readonly WindowAperture[], v: BeamView, out: number[] = []): number[] {
  out.length = 0;
  const key: number[] = [];
  const dist: number[] = [];
  windows.forEach((w, i) => {
    _sphere.set(w.centre, v.beamLengthM);
    key.push((sameStorey(w.centre.y, v) ? 4 : 0) + (v.frustum.intersectsSphere(_sphere) ? 2 : 0) + (sunFacing(w, v.lightDir) ? 1 : 0));
    dist.push(w.centre.distanceToSquared(v.player));
    out.push(i);
  });
  return out.sort((a, b) => key[b] - key[a] || dist[a] - dist[b] || a - b);
}

/**
 * The beam slots: at most MAX_WINDOW_BEAMS apertures lit, each weight easing
 * to 1 when selected and to 0 when dropped over BEAM_FADE_S. A fading-out
 * aperture holds its slot until its weight is 0; a new pick waits for a free slot.
 */
export class ApertureFader {
  readonly slots: { index: number; weight: number }[] = [];
  update(wanted: readonly number[], dtS: number): void {
    const step = Math.max(0, dtS) / BEAM_FADE_S;
    for (const s of this.slots) {
      const on = wanted.includes(s.index);
      s.weight = on ? Math.min(1, s.weight + step) : Math.max(0, s.weight - step);
    }
    for (let i = this.slots.length - 1; i >= 0; i--) {
      if (this.slots[i].weight === 0 && !wanted.includes(this.slots[i].index)) this.slots.splice(i, 1);
    }
    for (const index of wanted) {
      if (this.slots.length >= MAX_WINDOW_BEAMS) break;
      if (!this.slots.some((s) => s.index === index)) this.slots.push({ index, weight: 0 });
    }
  }
}

/**
 * Per-frame beams for a cell's windows, written into `out` (pooled). The
 * ranking picks up to MAX_WINDOW_BEAMS; each lit aperture's radiance is
 * scaled by its fader weight. `lightDir` is the unit direction the light
 * TRAVELS; `strength` the beam's irradiance scale, `tint` its colour.
 */
export class WindowBeams {
  readonly out: ApertureLight[] = [];
  readonly fader = new ApertureFader();
  private readonly pool: ApertureLight[] = [];
  private readonly ranked: number[] = [];
  private readonly wanted: number[] = [];
  private readonly view: BeamView;
  constructor(private readonly windows: readonly WindowAperture[], private readonly lengthM: number, floorsY?: readonly number[]) {
    for (let i = 0; i < MAX_WINDOW_BEAMS; i++) {
      this.pool.push({ position: new THREE.Vector3(), direction: new THREE.Vector3(), radiusM: 0, lengthM, irradiance: new THREE.Color() });
    }
    this.view = { player: new THREE.Vector3(), floorsY, frustum: new THREE.Frustum(), beamLengthM: lengthM, lightDir: new THREE.Vector3() };
  }

  /**
   * `origin` is the cell's world position; `playerWorld` the player's feet and
   * `frustumWorld` the camera frustum, both in world space; `dtS` the frame time.
   */
  update(origin: THREE.Vector3, lightDir: THREE.Vector3, strength: number, tint: THREE.Color,
    playerWorld: THREE.Vector3, frustumWorld: THREE.Frustum, dtS: number): ApertureLight[] {
    const v = this.view;
    v.player.copy(playerWorld).sub(origin);
    v.frustum.copy(frustumWorld);
    for (const pl of v.frustum.planes) pl.constant += pl.normal.dot(origin); // world -> cell frame
    v.lightDir.copy(lightDir);
    rankApertures(this.windows, v, this.ranked);
    this.wanted.length = 0;
    if (strength > 0) for (let i = 0; i < Math.min(MAX_WINDOW_BEAMS, this.ranked.length); i++) this.wanted.push(this.ranked[i]);
    this.fader.update(this.wanted, dtS);
    this.out.length = 0;
    for (const slot of this.fader.slots) {
      if (slot.weight <= 0 || strength <= 0) continue;
      const w = this.windows[slot.index];
      const a = this.pool[this.out.length];
      a.position.copy(w.centre).add(origin);
      a.radiusM = Math.sqrt(w.areaM2 / Math.PI);
      a.lengthM = this.lengthM;
      if (sunFacing(w, lightDir)) {
        a.direction.copy(lightDir);
        a.irradiance.copy(tint).multiplyScalar(strength * slot.weight);
      } else {
        a.direction.set(-w.outward.x, -FILL_TILT, -w.outward.z).normalize();
        a.irradiance.copy(tint).multiplyScalar(strength * SKY_FILL_SCALE * slot.weight);
      }
      this.out.push(a);
    }
    return this.out;
  }
}

type Body = { altitude: number; direction: { x: number; y: number; z: number } };
const SUN_TINT = new THREE.Color(1, 0.94, 0.82);
const MOON_TINT = new THREE.Color(0.72, 0.8, 1);

/**
 * The light a window lets in at this instant: the sun when it is up (faded
 * over its first 0.1 rad of altitude), else the highest moon at
 * `MOON_SCALE`, else nothing. Writes the travel direction and tint; returns
 * the strength relative to a full sun beam.
 */
export function windowSkyLight(sun: Body, moons: readonly Body[], lightDir: THREE.Vector3, tint: THREE.Color): number {
  if (sun.altitude > 0) {
    lightDir.set(-sun.direction.x, -sun.direction.y, -sun.direction.z);
    tint.copy(SUN_TINT);
    return THREE.MathUtils.smoothstep(sun.altitude, 0, 0.1);
  }
  let best: Body | null = null;
  for (const m of moons) if (m.altitude > 0 && (!best || m.altitude > best.altitude)) best = m;
  if (!best) return 0;
  lightDir.set(-best.direction.x, -best.direction.y, -best.direction.z);
  tint.copy(MOON_TINT);
  return MOON_SCALE;
}
