import roster from "./generated/races.json";

/**
 * The playable races.
 *
 * A race is a *body*: its own meshes, textures and skin tone, mounted on the
 * rig every character shares. That split is why adding a race costs under a
 * megabyte instead of duplicating the whole animation set, and why nothing in
 * combat, animation or inventory has to know which race is loaded.
 *
 * The roster is generated by the asset pipeline; this file only says what a
 * race means to the game.
 */

export type RaceId = string;

export type RaceDefinition = {
  id: RaceId;
  label: string;
  description: string;
  /** Race body GLB, relative to the deployment base URL. */
  asset: string;
  /** Content hash, used to bust a stale browser cache after a rebuild. */
  revision: string;
  /**
   * Biped slots each body mesh occupies, read from the NIF's own dismember
   * partitions at build time. Armour declares the same slots, so "this cuirass
   * hides the torso" is a set intersection rather than a hand-kept list that
   * silently rots when a body mesh is renamed.
   */
  meshBipedSlots: Readonly<Record<string, readonly number[]>>;
  /** How this race is coloured. See `Appearance`. */
  appearance: Appearance;
};

/**
 * What makes one character look different from another.
 *
 * Deliberately a *tint over shared art* rather than a texture set, which is how
 * Skyrim itself does it: every humanoid race uses the same body, the same
 * diffuse, and differs by head morph, eyes, hair and a colour. Ten races that
 * way cost one body's worth of download instead of ten.
 *
 * Applied at runtime, not baked. That is what a character creator needs — a
 * slider has to move a colour without rebuilding an asset — and it is also the
 * only way it works at all: a tint node between a texture and base colour is
 * not a shape the glTF exporter can write, so a baked one silently ships white.
 */
export type Appearance = {
  /** Multiplied over the skin diffuse. */
  skinTint: readonly [number, number, number];
  /** Multiplied over hair, horns and beards. */
  hairTint: readonly [number, number, number];
  /** Meshes the skin tint applies to. */
  skinMeshes: readonly string[];
  /** Meshes the hair tint applies to. */
  hairMeshes: readonly string[];
};

const NEUTRAL_APPEARANCE: Appearance = {
  skinTint: [1, 1, 1],
  hairTint: [1, 1, 1],
  skinMeshes: [],
  hairMeshes: [],
};

type BuiltRace = {
  label: string;
  description: string;
  asset: string;
  sha256: string;
  meshBipedSlots?: Record<string, number[]>;
  appearance?: {
    skinTint: [number, number, number];
    hairTint: [number, number, number];
    skinMeshes: string[];
    hairMeshes: string[];
  };
};

const BUILT = roster.races as unknown as Record<string, BuiltRace>;

export const RACES: Readonly<Record<RaceId, RaceDefinition>> = Object.fromEntries(
  Object.entries(BUILT).map(([id, race]) => [id, {
    id,
    label: race.label,
    description: race.description,
    asset: race.asset,
    revision: race.sha256.slice(0, 16),
    meshBipedSlots: race.meshBipedSlots ?? {},
    appearance: race.appearance ?? NEUTRAL_APPEARANCE,
  }]),
);

/** Display order: the roster's, which is the order a player expects to read. */
export const RACE_IDS: readonly RaceId[] = Object.keys(RACES);

/** The rig every race is posed by. */
export const RIG_REVISION = roster.rig.sha256.slice(0, 16);

/**
 * The race the support envelopes and fitted hurtbox were measured from. Every
 * race shares the body, hands and feet meshes those measurements depend on, so
 * one set is correct for all of them.
 */
export const REFERENCE_RACE: RaceId = roster.referenceRace;

export const DEFAULT_RACE: RaceId = REFERENCE_RACE;

export function raceById(id: RaceId): RaceDefinition {
  const race = RACES[id];
  if (!race) throw new RangeError(`unknown race: ${id}`);
  return race;
}
