/**
 * Stats lab text (apps/stats-lab) and the names of the stat system's records:
 * skills, attributes, races and classes (module 76 §116-§127; decision 0088).
 * Ids follow the record ids: `text.stat.skill.<kebab skill id>`,
 * `text.stat.attribute.<id>`, `text.stat.race.<id>`, `text.stat.class.<id>`.
 */
import type { TextEntry } from "./catalogue.js";

export const STATS_TEXT: readonly TextEntry[] = [
  { id: "text.stat.skill.long-blade", surface: "descriptive", text: "Long Blade", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.blunt", surface: "descriptive", text: "Blunt", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.axe", surface: "descriptive", text: "Axe", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.spear", surface: "descriptive", text: "Spear", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.short-blade", surface: "descriptive", text: "Short Blade", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.marksman", surface: "descriptive", text: "Marksman", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.hand-to-hand", surface: "descriptive", text: "Hand-to-Hand", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.block", surface: "descriptive", text: "Block", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.heavy-armor", surface: "descriptive", text: "Heavy Armor", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.medium-armor", surface: "descriptive", text: "Medium Armor", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.light-armor", surface: "descriptive", text: "Light Armor", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.unarmored", surface: "descriptive", text: "Unarmored", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.athletics", surface: "descriptive", text: "Athletics", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.acrobatics", surface: "descriptive", text: "Acrobatics", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.sneak", surface: "descriptive", text: "Sneak", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.security", surface: "descriptive", text: "Security", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.smithing", surface: "descriptive", text: "Smithing", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.mercantile", surface: "descriptive", text: "Mercantile", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.speechcraft", surface: "descriptive", text: "Speechcraft", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.alchemy", surface: "descriptive", text: "Alchemy", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.enchant", surface: "descriptive", text: "Enchant", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.alteration", surface: "descriptive", text: "Alteration", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.conjuration", surface: "descriptive", text: "Conjuration", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.destruction", surface: "descriptive", text: "Destruction", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.illusion", surface: "descriptive", text: "Illusion", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.mysticism", surface: "descriptive", text: "Mysticism", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.skill.restoration", surface: "descriptive", text: "Restoration", note: "Skill name on the character sheet and in the stats lab (module 76 \u00a7118). Morrowind's name where it kept one." },
  { id: "text.stat.attribute.strength", surface: "descriptive", text: "Strength", note: "Attribute name on the character sheet and in the stats lab (module 76 \u00a7117)." },
  { id: "text.stat.attribute.endurance", surface: "descriptive", text: "Endurance", note: "Attribute name on the character sheet and in the stats lab (module 76 \u00a7117)." },
  { id: "text.stat.attribute.agility", surface: "descriptive", text: "Agility", note: "Attribute name on the character sheet and in the stats lab (module 76 \u00a7117)." },
  { id: "text.stat.attribute.speed", surface: "descriptive", text: "Speed", note: "Attribute name on the character sheet and in the stats lab (module 76 \u00a7117)." },
  { id: "text.stat.attribute.willpower", surface: "descriptive", text: "Willpower", note: "Attribute name on the character sheet and in the stats lab (module 76 \u00a7117)." },
  { id: "text.stat.attribute.intelligence", surface: "descriptive", text: "Intelligence", note: "Attribute name on the character sheet and in the stats lab (module 76 \u00a7117)." },
  { id: "text.stat.attribute.personality", surface: "descriptive", text: "Personality", note: "Attribute name on the character sheet and in the stats lab (module 76 \u00a7117)." },
  { id: "text.stat.race.argonian", surface: "descriptive", text: "Argonian", note: "Playable race name (module 76 \u00a7127; the body roster in actors/generated/races.json uses the same word)." },
  { id: "text.stat.race.nord", surface: "descriptive", text: "Nord", note: "Playable race name (module 76 \u00a7127; the body roster in actors/generated/races.json uses the same word)." },
  { id: "text.stat.race.breton", surface: "descriptive", text: "Breton", note: "Playable race name (module 76 \u00a7127; the body roster in actors/generated/races.json uses the same word)." },
  { id: "text.stat.race.dunmer", surface: "descriptive", text: "Dunmer", note: "Playable race name (module 76 \u00a7127; the body roster in actors/generated/races.json uses the same word)." },
  { id: "text.stat.race.imperial", surface: "descriptive", text: "Imperial", note: "Playable race name (module 76 \u00a7127; the body roster in actors/generated/races.json uses the same word)." },
  { id: "text.stat.race.redguard", surface: "descriptive", text: "Redguard", note: "Playable race name (module 76 \u00a7127; the body roster in actors/generated/races.json uses the same word)." },
  { id: "text.stat.race.khajiit", surface: "descriptive", text: "Khajiit", note: "Playable race name (module 76 \u00a7127; the body roster in actors/generated/races.json uses the same word)." },
  { id: "text.stat.race.bosmer", surface: "descriptive", text: "Bosmer", note: "Playable race name (module 76 \u00a7127; the body roster in actors/generated/races.json uses the same word)." },
  { id: "text.stat.race.altmer", surface: "descriptive", text: "Altmer", note: "Playable race name (module 76 \u00a7127; the body roster in actors/generated/races.json uses the same word)." },
  { id: "text.stat.race.orsimer", surface: "descriptive", text: "Orsimer", note: "Playable race name (module 76 \u00a7127; the body roster in actors/generated/races.json uses the same word)." },
  { id: "text.stat.class.warrior", surface: "descriptive", text: "Warrior", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.knight", surface: "descriptive", text: "Knight", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.barbarian", surface: "descriptive", text: "Barbarian", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.scout", surface: "descriptive", text: "Scout", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.thief", surface: "descriptive", text: "Thief", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.assassin", surface: "descriptive", text: "Assassin", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.mage", surface: "descriptive", text: "Mage", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.spellsword", surface: "descriptive", text: "Spellsword", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.nightblade", surface: "descriptive", text: "Nightblade", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.healer", surface: "descriptive", text: "Healer", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.monk", surface: "descriptive", text: "Monk", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.kaal", surface: "descriptive", text: "Kaal (war-captain)", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.root-herald", surface: "descriptive", text: "Root-herald", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.tree-minder", surface: "descriptive", text: "Tree-minder", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.grave-singer", surface: "descriptive", text: "Grave-singer", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.shadowscale", surface: "descriptive", text: "Shadowscale-trained", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.marsh-guide", surface: "descriptive", text: "Marsh guide", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stat.class.reed-sail-hand", surface: "descriptive", text: "Reed-sail hand", note: "Preset class name on the creation screen (module 76 \u00a7119). The pan-Tamrielic classes keep their Elder Scrolls names; the province classes are named after offices in the lore dossiers." },
  { id: "text.stats-lab.male", surface: "ui", text: "Male" },
  { id: "text.stats-lab.female", surface: "ui", text: "Female" },
  { id: "text.stats-lab.title", surface: "ui", text: "Stats lab" },
  { id: "text.stats-lab.character", surface: "ui", text: "Character" },
  { id: "text.stats-lab.race", surface: "ui", text: "Race" },
  { id: "text.stats-lab.sex", surface: "ui", text: "Sex" },
  { id: "text.stats-lab.class", surface: "ui", text: "Class" },
  { id: "text.stats-lab.level", surface: "ui", text: "Level" },
  { id: "text.stats-lab.attributes", surface: "ui", text: "Attributes" },
  { id: "text.stats-lab.skills", surface: "ui", text: "Skills" },
  { id: "text.stats-lab.carried", surface: "ui", text: "Carried weight (kg)" },
  { id: "text.stats-lab.armour-rating", surface: "ui", text: "Armour rating" },
  { id: "text.stats-lab.derived", surface: "ui", text: "Derived values" },
  { id: "text.stats-lab.health", surface: "ui", text: "Health" },
  { id: "text.stats-lab.stamina", surface: "ui", text: "Stamina" },
  { id: "text.stats-lab.stamina-regen", surface: "ui", text: "Stamina per second" },
  { id: "text.stats-lab.magicka", surface: "ui", text: "Magicka" },
  { id: "text.stats-lab.magicka-regen", surface: "ui", text: "Magicka per second" },
  { id: "text.stats-lab.carry-capacity", surface: "ui", text: "Carry capacity (kg)" },
  { id: "text.stats-lab.burden", surface: "ui", text: "Burden" },
  { id: "text.stats-lab.breath", surface: "ui", text: "Breath (seconds)" },
  { id: "text.stats-lab.walk", surface: "ui", text: "Walk (m/s)" },
  { id: "text.stats-lab.sprint", surface: "ui", text: "Sprint (m/s)" },
  { id: "text.stats-lab.swim", surface: "ui", text: "Swim (m/s)" },
  { id: "text.stats-lab.jump", surface: "ui", text: "Jump height (m)" },
  { id: "text.stats-lab.safe-fall", surface: "ui", text: "Safe fall (m)" },
  { id: "text.stats-lab.weapon", surface: "ui", text: "Weapon skill" },
  { id: "text.stats-lab.damage-position", surface: "ui", text: "Damage position" },
  { id: "text.stats-lab.stamina-cost", surface: "ui", text: "Stamina cost" },
  { id: "text.stats-lab.strength-term", surface: "ui", text: "Strength term" },
  { id: "text.stats-lab.nock", surface: "ui", text: "Nock speed" },
  { id: "text.stats-lab.draw", surface: "ui", text: "Draw speed" },
  { id: "text.stats-lab.sway", surface: "ui", text: "Sway" },
  { id: "text.stats-lab.draw-stamina", surface: "ui", text: "Draw stamina" },
  { id: "text.stats-lab.stability", surface: "ui", text: "Block stability" },
  { id: "text.stats-lab.guard-stamina", surface: "ui", text: "Guard stamina" },
  { id: "text.stats-lab.curves", surface: "ui", text: "Skill curves" },
  { id: "text.stats-lab.curve-skill", surface: "ui", text: "Curve for" },
  { id: "text.stats-lab.skill-value", surface: "ui", text: "Skill" },
  { id: "text.stats-lab.multiplier", surface: "ui", text: "Multiplier" },
  { id: "text.stats-lab.ladder", surface: "ui", text: "Danger ladder" },
  { id: "text.stats-lab.band", surface: "ui", text: "Band" },
  { id: "text.stats-lab.enemy-health", surface: "ui", text: "Enemy health" },
  { id: "text.stats-lab.enemy-hit", surface: "ui", text: "Enemy light hit" },
  { id: "text.stats-lab.blows-to-kill-you", surface: "ui", text: "Blows that kill you" },
  { id: "text.stats-lab.mitigation", surface: "ui", text: "Armour stops" },
  { id: "text.stats-lab.harness", surface: "ui", text: "Balance harness" },
  { id: "text.stats-lab.run-harness", surface: "ui", text: "Run the harness" },
  { id: "text.stats-lab.invariant", surface: "ui", text: "Invariant" },
  { id: "text.stats-lab.result", surface: "ui", text: "Result" },
  { id: "text.stats-lab.pass", surface: "ui", text: "Pass" },
  { id: "text.stats-lab.fail", surface: "ui", text: "Fail" },
  { id: "text.stats-lab.tier-fast", surface: "ui", text: "Fast" },
  { id: "text.stats-lab.tier-mid", surface: "ui", text: "Mid" },
  { id: "text.stats-lab.tier-fat", surface: "ui", text: "Fat" },
  { id: "text.stats-lab.tier-overloaded", surface: "ui", text: "Overloaded" },
  { id: "text.stats-lab.preset-reference", surface: "ui", text: "The Marsh Hand (reference)" },
  { id: "text.stats-lab.climb", surface: "ui", text: "Climb" },
  { id: "text.stats-lab.wall-height", surface: "ui", text: "Wall height (m)" },
  { id: "text.stats-lab.climb-seconds", surface: "ui", text: "Seconds" },
  { id: "text.stats-lab.climb-cost", surface: "ui", text: "Stamina used" },
  { id: "text.stats-lab.climb-in-one-go", surface: "ui", text: "In one go" },
  { id: "text.stats-lab.yes", surface: "ui", text: "Yes" },
  { id: "text.stats-lab.no", surface: "ui", text: "No" },
  { id: "text.stats-lab.band-damage-position", surface: "ui", text: "Damage position (band)" },
  { id: "text.stats-lab.band-stamina-cost", surface: "ui", text: "Stamina cost (band)" },
  { id: "text.stats-lab.band-wear", surface: "ui", text: "Wear" },
  { id: "text.stats-lab.band-backstab", surface: "ui", text: "Backstab" },
  { id: "text.stats-lab.band-nock-speed", surface: "ui", text: "Nock speed (band)" },
  { id: "text.stats-lab.band-draw-speed", surface: "ui", text: "Draw speed (band)" },
  { id: "text.stats-lab.band-sway", surface: "ui", text: "Sway (band)" },
  { id: "text.stats-lab.band-draw-stamina", surface: "ui", text: "Draw stamina (band)" },
  { id: "text.stats-lab.band-stamina-damage", surface: "ui", text: "Stamina damage to the target" },
  { id: "text.stats-lab.band-stability", surface: "ui", text: "Stability (band)" },
  { id: "text.stats-lab.band-guard-stamina", surface: "ui", text: "Guard stamina (band)" },
  { id: "text.stats-lab.band-rating", surface: "ui", text: "Armour rating (band)" },
  { id: "text.stats-lab.band-effective-weight", surface: "ui", text: "Effective weight" },
  { id: "text.stats-lab.band-sprint-drain", surface: "ui", text: "Sprint drain" },
  { id: "text.stats-lab.band-climb-speed", surface: "ui", text: "Climb speed" },
  { id: "text.stats-lab.band-climb-stamina", surface: "ui", text: "Climb stamina drain" },
  { id: "text.stats-lab.band-noise-radius", surface: "ui", text: "Noise radius" },
  { id: "text.stats-lab.band-visibility", surface: "ui", text: "Visibility" },
  { id: "text.stats-lab.invariant.reference-equivalence", surface: "ui", text: "The reference character matches the combat sandbox" },
  { id: "text.stats-lab.invariant.d5-overmatches-a-beginner", surface: "ui", text: "A D5 enemy near one-shots a beginner, who barely scratches it back" },
  { id: "text.stats-lab.invariant.band-is-fair-for-its-build", surface: "ui", text: "Each danger band is a fair fight for the build it expects" },
  { id: "text.stats-lab.invariant.overmatch-is-lethal", surface: "ui", text: "An enemy above your band kills you in a few blows" },
  { id: "text.stats-lab.invariant.armour-never-trivialises", surface: "ui", text: "No armour makes you immune to hits" },
  { id: "text.stats-lab.invariant.getting-hit-matters", surface: "ui", text: "Every build dies in the planned number of blows" },
  { id: "text.stats-lab.invariant.climbing-is-a-real-cost", surface: "ui", text: "Climbing costs real stamina" },
  { id: "text.stats-lab.invariant.a-whole-game-holds-together", surface: "ui", text: "Every whole-game run can be finished" },
  { id: "text.stats-lab.invariant.content-model-is-a-playthrough", surface: "ui", text: "An hour of play looks like real play" },
  { id: "text.stats-lab.invariant.morrowind-known-answer", surface: "ui", text: "The engine reproduces Morrowind's levelling pace" },
  { id: "text.stats-lab.invariant.no-level-bearing-skill-is-dead-content", surface: "ui", text: "Every major and minor skill gets used" },
  { id: "text.stats-lab.invariant.no-deferral-advantage", surface: "ui", text: "Saving up vastei gives no advantage" },
  { id: "text.stats-lab.invariant.affordability-band", surface: "ui", text: "Each level-up buys a sensible number of points" },
  { id: "text.stats-lab.invariant.every-build-can-finish", surface: "ui", text: "Every build can beat the final fight" },
  { id: "text.stats-lab.invariant.breath-margins", surface: "ui", text: "Breath lasts long enough for a competent swimmer; an untrained one runs out first" },
  { id: "text.stats-lab.invariant.crafting-loops-are-bounded", surface: "ui", text: "Crafting cannot feed itself without limit" },
  { id: "text.stats-lab.invariant.soft-requirements-never-block", surface: "ui", text: "Heavy gear costs stamina but never locks you out" },
  { id: "text.stats-lab.invariant.clean-play-pays", surface: "ui", text: "Careful fighting pays for itself" },
  { id: "text.stats-lab.invariant.vastei-farming-is-throttled", surface: "ui", text: "Maxing an attribute at level 10 costs far more vastei than a level's earnings" },
];
