import type { AnimationState } from "../core/types";
import manifest from "./generated/rig-skyrim-humanoid.animations.json";

/**
 * Runtime animation contract, generated by the asset pipeline
 * (elder-scrolls-asset-pipeline). The game references only SEMANTIC state names;
 * the mapping to any Bethesda source clip lives entirely in the pipeline. To
 * swap a clip (e.g. ROLL) you rebuild the rig — no game-code change.
 *
 * The rig is the *shared* half of a character: one skeleton and one set of
 * clips, loaded once and posed by whichever race body is mounted on it. Race
 * meshes live in their own GLBs (`actors/races.ts`), because shipping the
 * animations with each of them would duplicate several megabytes per race.
 */

export type RootMotionPolicy = "strip" | "consume";
export type SupportMode = "penetration" | "floor-contact" | "airborne";

export type SupportPhase = {
  /** Source-clip seconds; phases use the half-open interval [startTime, endTime). */
  startTime: number;
  endTime: number;
  mode: SupportMode;
};

export type SupportEnvelope = {
  /** Runtime source time represented by the first baked visible-surface sample. */
  sampleStartTimeSeconds?: number;
  sampleIntervalSeconds: number;
  /** Lowest deformed visible surface, in runtime metres relative to the actor root. */
  surfaceMinY: number[];
  /** Lowest foot/toe bone origin, sampled beside surfaceMinY in runtime metres. */
  soleMarkerMinY?: number[];
  /** Identity-preserving foot/toe origins sampled beside surfaceMinY. */
  soleMarkerYById?: Record<string, number[]>;
  /** Clearance from each marker to nearby visible vertices weighted by it. */
  soleMarkerClearanceYById?: Record<string, number[]>;
  /** Lowest nearby visible point in each marker bone's local, unscaled GLB coordinates. */
  soleMarkerPointBoneLocalById?: Record<string, [number, number, number][]>;
};

export type ClipConfig = {
  /** Which downloadable pack ships this clip. See {@link AnimationPack}. */
  pack?: string;
  looping: boolean;
  playbackRate: number;
  rootMotion: RootMotionPolicy;
  /** Source clip length in seconds, before playbackRate. */
  sourceDuration: number | null;
  /** Optional source-time in-point used when this semantic action starts. */
  playbackStartTime: number | null;
  /** Optional source-time out-point; playback intentionally hands off here. */
  playbackEndTime: number | null;
  /** Pose-blend duration when entering this clip. */
  crossFadeDuration?: number | null;
  /** Optional pose-blend duration when leaving this clip. */
  crossFadeOutDuration?: number | null;
  /** Default relationship between the authored visible surface and its support. */
  supportMode?: SupportMode;
  /** Source-time overrides for airborne or deliberately floor-bound phases. */
  supportPhases?: SupportPhase[];
  /** Pipeline-baked visible-surface samples; never skinned at gameplay runtime. */
  supportEnvelope?: SupportEnvelope | null;
  /**
   * Measured ground speed (m/s) this clip's authored stride is timed for, from
   * the planar velocity of its planted sole. ~0 for standing actions.
   */
  authoredGroundSpeed?: number | null;
  /** Authored net root translation (metres, character space) or null. */
  rootMotionDelta: [number, number, number] | null;
  provenance: string;
};

type RigManifest = {
  rootBone: string;
  /**
   * Quaternion XYZW taking weapon-asset space into any socket bone's local
   * space on this rig. Weapon GLBs keep their native attach-node axes while
   * the imported armature stores bones in Blender's convention; that fixed
   * offset belongs to the skeleton, so every weapon inherits it and none of
   * them carries a hand-tuned rotation.
   */
  socketRotation?: [number, number, number, number];
  sockets: {
    rightHand: string;
    leftHand: string;
    weapon: string;
    weaponFallback: string;
    sheath: string;
    /**
     * Not an attachment point: the bone a first-person view collapses so the
     * camera is not inside a face. Named by the rig because which bone is a
     * head is a property of the skeleton, not of the game.
     */
    head?: string;
  };
  recommendedScale: number;
  targetHeightMeters: number;
};

export type HurtboxSegment = {
  /** Rig bone this capsule rides, in the manifest's own naming. */
  bone: string;
  /** Capsule axis endpoints in unscaled bone-local space. */
  from: [number, number, number];
  to: [number, number, number];
  /** Runtime metres. */
  radius: number;
  halfLength: number;
};

/**
 * One separately downloadable slice of the rig's clip set.
 *
 * The rig is built once and emitted as several GLBs that share a skeleton:
 * `core` (what a body can do regardless of what it holds) plus one pack per
 * weapon family. An actor fetches only the packs it can actually play, so
 * adding a moveset for a weapon nobody has equipped costs a player nothing.
 * Adding a *new* weapon family is a pipeline config entry and an entry in
 * `MOVESET_PACKS` — no change to loading, binding or the actor.
 */
export type AnimationPack = {
  /** GLB filename, beside the core rig in `character-assets/files/`. */
  asset: string;
  description: string;
  /** Binds the pack to the exact binary this manifest describes. */
  sha256: string;
  bytes: number;
  /** Packs that must be loaded alongside this one. */
  requires?: string[];
  clips: string[];
};

type CharacterManifest = {
  assetSha256?: string;
  packs?: Record<string, AnimationPack>;
  rig: RigManifest;
  supportCalibration?: {
    /** Near-plane guard for one fixed-step overshoot at physical impact. */
    airborneImpactProximityMeters?: number;
    /** Legacy scalar-marker fallback; current manifests use bone-local 3D candidates instead. */
    crossFadeSoleSafetyMarginMeters?: number;
  };
  hurtbox?: { segments: HurtboxSegment[] };
  animations: Record<string, ClipConfig>;
};

const CHARACTER_MANIFEST = manifest as unknown as CharacterManifest;
const RIG = CHARACTER_MANIFEST.rig;
const ANIMATIONS = CHARACTER_MANIFEST.animations;

/** The always-loaded pack: everything a body can do without holding anything. */
export const CORE_ANIMATION_PACK = "core";

export const ANIMATION_PACKS: Readonly<Record<string, AnimationPack>> =
  CHARACTER_MANIFEST.packs ?? {};

export const RIG_GLB = ANIMATION_PACKS[CORE_ANIMATION_PACK]?.asset ?? "rig-skyrim-humanoid.glb";

/** GLB filename for a pack id, or null if the build does not contain it. */
export function animationPackAsset(pack: string): string | null {
  return ANIMATION_PACKS[pack]?.asset ?? null;
}

/**
 * Expand a wanted pack set into everything that must actually be loaded:
 * `core` always, the requested packs, and whatever they declare they need.
 *
 * Returned in a stable order so the result can be used as a component key —
 * a set that reorders between renders would remount the actor for no reason.
 */
export function resolveAnimationPacks(wanted: Iterable<string>): readonly string[] {
  const resolved = new Set<string>([CORE_ANIMATION_PACK]);
  const pending = [...wanted];
  while (pending.length > 0) {
    const pack = pending.pop()!;
    if (!ANIMATION_PACKS[pack] || resolved.has(pack)) continue;
    resolved.add(pack);
    pending.push(...(ANIMATION_PACKS[pack].requires ?? []));
  }
  // Manifest order, which is build order: core first, shared packs before the
  // weapon packs that borrow from them.
  return Object.keys(ANIMATION_PACKS).filter((pack) => resolved.has(pack));
}

/**
 * Files to fetch for a resolved pack list.
 *
 * Each carries its own content hash as a cache-busting revision, so rebuilding
 * one moveset does not invalidate the others and a stale pack cannot be paired
 * with a fresh manifest by a CDN.
 */
export function animationPackFiles(packs: readonly string[]) {
  return packs.flatMap((pack) => {
    const entry = ANIMATION_PACKS[pack];
    return entry ? [{ pack, asset: entry.asset, revision: entry.sha256.slice(0, 16) }] : [];
  });
}

/** Which pack ships a clip. Unknown states answer `core`, as the fallback does. */
export function clipPack(state: AnimationState): string {
  return ANIMATIONS[state]?.pack ?? CORE_ANIMATION_PACK;
}

/** The packs a set of semantic states needs between them, already expanded. */
export function packsForStates(states: Iterable<AnimationState>): readonly string[] {
  return resolveAnimationPacks([...states].map(clipPack));
}


export const RIG_ROOT_BONE = RIG.rootBone;
export const RIG_SOCKETS = RIG.sockets;

/**
 * Skeleton-fitted combat volume, measured from this character's own skin by
 * the pipeline. A different skeleton or silhouette produces a different set
 * with no game-code change; an actor with no fitted hurtbox falls back to the
 * navigation capsule.
 */
export const HURTBOX_SEGMENTS: readonly HurtboxSegment[] =
  CHARACTER_MANIFEST.hurtbox?.segments ?? [];

/**
 * three.js strips whitespace and reserved characters from Object3D names on
 * load, so a rig bone is looked up by its sanitized form rather than the name
 * the skeleton and manifest use. Mirrors `PropertyBinding.sanitizeNodeName`.
 */
export function sanitizeBoneName(name: string) {
  return name.replace(/\s/g, "_").replace(/[[\].:/]/g, "");
}
export const RIG_SOCKET_ROTATION: readonly [number, number, number, number] =
  RIG.socketRotation ?? [0, 0, 0, 1];
export const CHARACTER_SCALE = RIG.recommendedScale;
export const CHARACTER_TARGET_HEIGHT = RIG.targetHeightMeters;
export const AIRBORNE_IMPACT_PROXIMITY_METERS = Math.max(
  0,
  CHARACTER_MANIFEST.supportCalibration?.airborneImpactProximityMeters ?? 0,
);
export const CROSS_FADE_SOLE_SAFETY_MARGIN_METERS = Math.max(
  0,
  CHARACTER_MANIFEST.supportCalibration?.crossFadeSoleSafetyMarginMeters ?? 0,
);

const FALLBACK: ClipConfig = {
  looping: false,
  playbackRate: 1,
  rootMotion: "strip",
  sourceDuration: null,
  playbackStartTime: null,
  playbackEndTime: null,
  crossFadeDuration: 0.12,
  crossFadeOutDuration: null,
  supportMode: "penetration",
  supportPhases: [],
  supportEnvelope: null,
  authoredGroundSpeed: null,
  rootMotionDelta: null,
  provenance: "",
};

export function clipConfig(state: AnimationState): ClipConfig {
  return ANIMATIONS[state] ?? FALLBACK;
}

/**
 * Resolve a transition blend without hard-coding semantic edges in the actor.
 * An explicit gameplay command wins; otherwise an authored outgoing handoff
 * can override the incoming clip's ordinary entry blend.
 */
export function transitionCrossFadeDuration(
  incomingState: AnimationState,
  outgoingState: AnimationState,
  commandOverride: number | null,
) {
  return commandOverride
    ?? clipConfig(outgoingState).crossFadeOutDuration
    ?? clipConfig(incomingState).crossFadeDuration
    ?? 0.12;
}

/** Measured travel speed the authored stride is timed for, or null. */
export function clipAuthoredGroundSpeed(state: AnimationState): number | null {
  return clipConfig(state).authoredGroundSpeed ?? null;
}

/** Source-time span that runtime playback should cover before handing off. */
export function clipPlaybackSourceSpan(state: AnimationState): number | null {
  const config = clipConfig(state);
  const end = config.playbackEndTime ?? config.sourceDuration;
  return end == null ? null : Math.max(0, end - (config.playbackStartTime ?? 0));
}

/** Wall-clock seconds needed to show the configured authored source span. */
export function clipPlaybackDuration(state: AnimationState): number | null {
  const config = clipConfig(state);
  const span = clipPlaybackSourceSpan(state);
  return span == null || config.playbackRate <= 0 ? null : span / config.playbackRate;
}

/**
 * Semantic states that represent free locomotion (mixer-driven, self-timed).
 * JUMP_START/JUMP_LAND are included even though they are one-shot combat-like
 * clips: they play while the player's `CombatAction` stays "idle" (jumping is
 * not a combat action), so the shared action clock keeps free-running instead
 * of resetting at takeoff/landing. Driving them externally from that stale
 * clock clamps them to their last frame from the very first rendered frame.
 * Self-timing avoids the stale clock entirely.
 */
export const LOCOMOTION_STATES: ReadonlySet<AnimationState> = new Set<AnimationState>([
  "IDLE",
  "SWORD_IDLE",
  "WALK",
  "WALK_BACK",
  "STRAFE_LEFT",
  "STRAFE_RIGHT",
  "RUN",
  "SPRINT",
  "GUARD",
  "JUMP_IDLE",
  "JUMP_START",
  "JUMP_LAND",
  "JUMP_LAND_LEFT",
  "JUMP_LAND_RIGHT",
  // Carrying a bow is ordinary locomotion: self-timed, and scaled to the
  // actor's ground speed like every other stride.
  "BOW_IDLE",
  "BOW_WALK",
  "BOW_WALK_BACK",
  "BOW_STRAFE_LEFT",
  "BOW_STRAFE_RIGHT",
  "BOW_RUN",
  // Held at full draw is a *loop*, like a raised guard: it should run on its
  // own clock and wrap cleanly. Driving it from the action clock walks it
  // further into the source idle the longer the string is held, which is how a
  // three-second hold ends up somewhere the clip never meant to be.
  "BOW_DRAWN",
  // Crouched movement is ordinary locomotion that happens to be low: self-timed
  // and cadence-matched to the actor's ground speed like any other stride.
  "CROUCH_IDLE",
  "CROUCH_WALK",
  "CROUCH_WALK_BACK",
  "CROUCH_STRAFE_LEFT",
  "CROUCH_STRAFE_RIGHT",
  "SWORD_CROUCH_IDLE",
  // Two-handed carriage and locomotion. The attacks are combat actions on the
  // gameplay clock, exactly as the one-handed ones are; only these are free.
  "GREATSWORD_IDLE",
  "GREATSWORD_WALK",
  "GREATSWORD_WALK_BACK",
  "GREATSWORD_STRAFE_LEFT",
  "GREATSWORD_STRAFE_RIGHT",
  "GREATSWORD_RUN",
  "GREATSWORD_SPRINT",
  "GREATSWORD_GUARD",
  "GREATAXE_IDLE",
  "GREATAXE_SPRINT",
  // A raised shield is a held stance, like the weapon guard beside it.
  "SHIELD_GUARD",
]);

/** Every semantic state the built GLB is expected to contain. */
export const MANIFEST_STATES = Object.keys(ANIMATIONS) as AnimationState[];
