"""`wb.py packet-shots PLACE_ID`: a walk packet's contents list and pictures,
both from the PUBLISHED bundle (walk 6 item 4: the walk-5 Riverwalk packet
attached a round-3 render of a layout the resite had since replaced, and its
contents line was written by hand from the design brief).

The contents list is generated from the bundle's placements and doors. The
pictures reuse `render.render_round` on the place's applied scene, and only
after a read-back shows every published building, run piece and fixture at
its scene pose (round-recipe 3b); a scene that disagrees is refused. Every
picture's caption and `manifest.json` carry the git HEAD and the bundle's
sha256 (index.json), which `owner_inbox.py --attach` checks."""
from __future__ import annotations

import hashlib
import json
import subprocess
from collections import Counter, defaultdict
from pathlib import Path

from . import paths

POSE_TOL_M = 0.05           # x/z read-back tolerance, scene pivot vs bundle positionM
SCENE_KINDS = {"settlement"}  # placements the scene must carry; landmarks/effects the
                              # compile adds are listed as not drawn


def bundle_path(place: str, province: Path | None = None) -> Path:
    return (province or paths.PROVINCE) / "settlements" / f"{place}.json"


def bundle_sha(place: str, province: Path | None = None) -> str:
    """The sha256 index.json publishes for the place (what the studio loads);
    the file's own hash when the index has no row."""
    prov = province or paths.PROVINCE
    idx = json.loads((prov / "settlements" / "index.json").read_text())
    row = next((r for r in idx.get("places", []) if r["id"] == place), None)
    if row and row.get("sha256"):
        return row["sha256"]
    return hashlib.sha256(bundle_path(place, prov).read_bytes()).hexdigest()


def git_head() -> str:
    return subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=paths.REPO_ROOT,
                          capture_output=True, text=True, check=True).stdout.strip()


def _stem(asset: str) -> str:
    return asset.rsplit("/", 1)[-1]


def classify(pid: str, site_id: str) -> tuple[str, str]:
    """(group, owner) for a placement id: building / run / fixture / landmark /
    other, and the parcel or run it belongs to."""
    rest = pid.removeprefix(site_id + ".")
    if ".assembly." in rest:
        return "fixture", rest.split(".assembly.", 1)[0]
    if rest.endswith(".building"):
        return "building", rest.removesuffix(".building")
    if ".piece." in rest:
        return "run", rest.rsplit(".piece.", 1)[0]
    if rest.startswith("landmark."):
        return "landmark", rest
    return "other", rest


def contents(bundle: dict) -> dict:
    """The packet's contents, counted from the bundle (never from a brief)."""
    site = bundle["settlement"]
    site_id = site["id"]
    ids = set(site.get("placementIds") or [p["id"] for p in bundle["placements"]])
    placed = [p for p in bundle["placements"] if p["id"] in ids]
    buildings, runs, fixtures, landmarks, other = Counter(), defaultdict(list), Counter(), Counter(), Counter()
    for p in placed:
        group, owner = classify(p["id"], site_id)
        asset = p["assetId"]
        if p.get("kind") == "effect":
            other[f"effect {_stem(asset)}"] += 1
        elif group == "building":
            buildings[asset] += 1
        elif group == "run":
            runs[owner].append(asset)
        elif group == "fixture":
            fixtures[asset] += 1
        elif group == "landmark" or p.get("kind") == "landmark":
            landmarks[asset] += 1
        else:
            other[asset] += 1
    run_rows = Counter()
    for owner, assets in runs.items():
        run_rows[tuple(sorted(set(assets)))] += 1
    doors = [d for d in bundle.get("doors", []) if d.get("settlementId", site_id) == site_id]
    cells = sorted({(d.get("interiorClaim") or {}).get("cellId") for d in doors} - {None})
    return {
        "placeId": bundle.get("placeId", site_id),
        "placements": len(placed),
        "buildings": [{"asset": a, "count": n} for a, n in sorted(buildings.items())],
        "runs": [{"assets": list(k), "runs": n,
                  "pieces": sum(len(v) for v in runs.values() if tuple(sorted(set(v))) == k)}
                 for k, n in sorted(run_rows.items())],
        "fixtures": [{"asset": a, "count": n} for a, n in sorted(fixtures.items())],
        "landmarks": [{"asset": a, "count": n} for a, n in sorted(landmarks.items())],
        "other": [{"asset": a, "count": n} for a, n in sorted(other.items())],
        "doors": len(doors), "interiors": cells,
    }


def contents_md(c: dict, head: str, sha: str) -> str:
    fam = lambda a: f"{_stem(a)} (`{a}`)"
    lines = [f"# Contents of {c['placeId']}", "",
             f"Generated by `wb.py packet-shots` from the published bundle "
             f"(sha256 {sha[:12]}, HEAD {head}); {c['placements']} placements.", ""]
    lines += [f"- {r['count']} building {fam(r['asset'])}" for r in c["buildings"]]
    lines += [f"- {r['runs']} run{'s' if r['runs'] != 1 else ''} of "
              f"{', '.join(_stem(a) for a in r['assets'])} ({r['pieces']} pieces)" for r in c["runs"]]
    lines += [f"- {r['count']} fixture {fam(r['asset'])}" for r in c["fixtures"]]
    lines += [f"- {r['count']} landmark {fam(r['asset'])}" for r in c["landmarks"]]
    lines += [f"- {r['count']} other {r['asset']}" for r in c["other"]]
    lines.append(f"- {c['doors']} doors; interiors: {', '.join(c['interiors']) or 'none'}")
    return "\n".join(lines) + "\n"


def read_back(bundle: dict, scene) -> dict:
    """Every scene-kind placement must map to a scene piece at its published
    x/z (round-recipe 3b); returns missing / moved / not drawn."""
    from .rules import bundle_uid
    site_id = bundle["settlement"]["id"]
    by = {p.uid: p for p in scene.pieces}
    missing, moved, not_drawn = [], [], []
    for p in bundle["placements"]:
        uid = bundle_uid(scene, p["id"], site_id)
        q = by.get(uid)
        if q is None:
            (missing if p.get("kind") in SCENE_KINDS else not_drawn).append(p["id"])
            continue
        d = max(abs(q.x - p["positionM"][0]), abs(q.z - p["positionM"][2]))
        if d > POSE_TOL_M:
            moved.append({"id": p["id"], "offM": round(d, 2)})
    return {"missing": missing, "moved": moved, "notDrawn": not_drawn}


def stamp(png: Path, text: str) -> None:
    from PIL import Image
    from .render import _caption
    img = Image.open(png).convert("RGB")
    _caption(img, text)
    img.save(png)


def _render_published(place: str, bundle: dict) -> tuple[list[dict], dict]:
    """render_round on the place's applied scene, after the read-back."""
    from .scene import Scene
    import wb
    summary = paths.OUTPUT / "apply" / f"{place}.json"
    if not summary.exists():
        raise ValueError(f"packet-shots: no apply summary {summary}: run `wb.py apply <layout> --full`")
    scene = Scene.load(Path(json.loads(summary.read_text())["scene"]))
    rb = read_back(bundle, scene)
    if rb["missing"] or rb["moved"]:
        raise ValueError(
            f"packet-shots: scene {scene.path} is not the published place "
            f"({len(rb['missing'])} missing, {len(rb['moved'])} moved, e.g. "
            f"{(rb['missing'] + [m['id'] for m in rb['moved']])[:3]}): run "
            f"`wb.py apply <committed layout> --full` and re-run (round-recipe 3b)")
    from . import render
    got = render.render_round(wb.place_catalogue(scene.placeId), scene, "auto")
    return [{"png": s["png"], "subject": s.get("subject"), "view": s.get("view")}
            for s in json.loads(Path(got["manifest"]).read_text())["shots"]], \
        {"scene": str(scene.path), "readBack": rb, "round": got["dir"]}


def run(place: str, out: Path, province: Path | None = None, render_fn=None,
        head: str | None = None) -> dict:
    """Write contents.md/.json, the stamped pictures and manifest.json to OUT."""
    import shutil
    bundle = json.loads(bundle_path(place, province).read_text())
    sha = bundle_sha(place, province)
    head = head or git_head()
    out.mkdir(parents=True, exist_ok=True)
    c = contents(bundle)
    stampd = {"placeId": place, "gitHead": head, "bundleSha256": sha,
              "bundle": str(bundle_path(place, province))}
    (out / "contents.json").write_text(json.dumps({**stampd, **c}, indent=1) + "\n")
    (out / "contents.md").write_text(contents_md(c, head, sha))
    shots, meta = (render_fn or _render_published)(place, bundle)
    pictures = []
    for s in shots:
        dst = out / Path(s["png"]).name
        shutil.copyfile(s["png"], dst)
        caption = f"{place} | HEAD {head} | bundle {sha[:12]} | {s.get('subject') or s.get('view')}"
        stamp(dst, caption)
        pictures.append({"png": dst.name, "caption": caption, "subject": s.get("subject"),
                         "view": s.get("view")})
    manifest = {"schemaVersion": 1, "writtenBy": "wb.py packet-shots", **stampd,
                "pictures": pictures, **meta}
    (out / "manifest.json").write_text(json.dumps(manifest, indent=1) + "\n")
    return {"out": str(out), "contents": str(out / "contents.md"),
            "manifest": str(out / "manifest.json"), "pictures": len(pictures),
            "gitHead": head, "bundleSha256": sha[:12]}
